// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr5ade676bd5b81c209ce2e5c6Params creates a new Nr5ade676bd5b81c209ce2e5c6Params object
// with the default values initialized.
func NewNr5ade676bd5b81c209ce2e5c6Params() *Nr5ade676bd5b81c209ce2e5c6Params {
	var ()
	return &Nr5ade676bd5b81c209ce2e5c6Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5ade676bd5b81c209ce2e5c6ParamsWithTimeout creates a new Nr5ade676bd5b81c209ce2e5c6Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5ade676bd5b81c209ce2e5c6ParamsWithTimeout(timeout time.Duration) *Nr5ade676bd5b81c209ce2e5c6Params {
	var ()
	return &Nr5ade676bd5b81c209ce2e5c6Params{

		timeout: timeout,
	}
}

// NewNr5ade676bd5b81c209ce2e5c6ParamsWithContext creates a new Nr5ade676bd5b81c209ce2e5c6Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5ade676bd5b81c209ce2e5c6ParamsWithContext(ctx context.Context) *Nr5ade676bd5b81c209ce2e5c6Params {
	var ()
	return &Nr5ade676bd5b81c209ce2e5c6Params{

		Context: ctx,
	}
}

// NewNr5ade676bd5b81c209ce2e5c6ParamsWithHTTPClient creates a new Nr5ade676bd5b81c209ce2e5c6Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5ade676bd5b81c209ce2e5c6ParamsWithHTTPClient(client *http.Client) *Nr5ade676bd5b81c209ce2e5c6Params {
	var ()
	return &Nr5ade676bd5b81c209ce2e5c6Params{
		HTTPClient: client,
	}
}

/*Nr5ade676bd5b81c209ce2e5c6Params contains all the parameters to send to the API endpoint
for the 5ade676bd5b81c209ce2e5c6 operation typically these are written to a http.Request
*/
type Nr5ade676bd5b81c209ce2e5c6Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*Body
	  The new explicit list item

	*/
	Body interface{}
	/*EntityID
	  Format - guid. The Pattern.Any entity ID.

	*/
	EntityID string
	/*ItemID
	  The explicit list item ID.

	*/
	ItemID int64
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithTimeout(timeout time.Duration) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithContext(ctx context.Context) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithHTTPClient(client *http.Client) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithAppID(appID string) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithBody adds the body to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithBody(body interface{}) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetBody(body interface{}) {
	o.Body = body
}

// WithEntityID adds the entityID to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithEntityID(entityID string) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetEntityID(entityID)
	return o
}

// SetEntityID adds the entityId to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetEntityID(entityID string) {
	o.EntityID = entityID
}

// WithItemID adds the itemID to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithItemID(itemID int64) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetItemID(itemID)
	return o
}

// SetItemID adds the itemId to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetItemID(itemID int64) {
	o.ItemID = itemID
}

// WithVersionID adds the versionID to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WithVersionID(versionID string) *Nr5ade676bd5b81c209ce2e5c6Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 5ade676bd5b81c209ce2e5c6 params
func (o *Nr5ade676bd5b81c209ce2e5c6Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5ade676bd5b81c209ce2e5c6Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param entityId
	if err := r.SetPathParam("entityId", o.EntityID); err != nil {
		return err
	}

	// path param itemId
	if err := r.SetPathParam("itemId", swag.FormatInt64(o.ItemID)); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
