// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5ade55bdd5b81c209ce2e5aaReader is a Reader for the Nr5ade55bdd5b81c209ce2e5aa structure.
type Nr5ade55bdd5b81c209ce2e5aaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5ade55bdd5b81c209ce2e5aaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5ade55bdd5b81c209ce2e5aaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5ade55bdd5b81c209ce2e5aaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5ade55bdd5b81c209ce2e5aaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5ade55bdd5b81c209ce2e5aaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5ade55bdd5b81c209ce2e5aaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5ade55bdd5b81c209ce2e5aaOK creates a Nr5ade55bdd5b81c209ce2e5aaOK with default headers values
func NewNr5ade55bdd5b81c209ce2e5aaOK() *Nr5ade55bdd5b81c209ce2e5aaOK {
	return &Nr5ade55bdd5b81c209ce2e5aaOK{}
}

/*Nr5ade55bdd5b81c209ce2e5aaOK handles this case with default header values.

A Pattern.Any entity model info.
*/
type Nr5ade55bdd5b81c209ce2e5aaOK struct {
}

func (o *Nr5ade55bdd5b81c209ce2e5aaOK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}][%d] 5ade55bdd5b81c209ce2e5aaOK ", 200)
}

func (o *Nr5ade55bdd5b81c209ce2e5aaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade55bdd5b81c209ce2e5aaBadRequest creates a Nr5ade55bdd5b81c209ce2e5aaBadRequest with default headers values
func NewNr5ade55bdd5b81c209ce2e5aaBadRequest() *Nr5ade55bdd5b81c209ce2e5aaBadRequest {
	return &Nr5ade55bdd5b81c209ce2e5aaBadRequest{}
}

/*Nr5ade55bdd5b81c209ce2e5aaBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5ade55bdd5b81c209ce2e5aaBadRequest struct {
}

func (o *Nr5ade55bdd5b81c209ce2e5aaBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}][%d] 5ade55bdd5b81c209ce2e5aaBadRequest ", 400)
}

func (o *Nr5ade55bdd5b81c209ce2e5aaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade55bdd5b81c209ce2e5aaUnauthorized creates a Nr5ade55bdd5b81c209ce2e5aaUnauthorized with default headers values
func NewNr5ade55bdd5b81c209ce2e5aaUnauthorized() *Nr5ade55bdd5b81c209ce2e5aaUnauthorized {
	return &Nr5ade55bdd5b81c209ce2e5aaUnauthorized{}
}

/*Nr5ade55bdd5b81c209ce2e5aaUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5ade55bdd5b81c209ce2e5aaUnauthorized struct {
}

func (o *Nr5ade55bdd5b81c209ce2e5aaUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}][%d] 5ade55bdd5b81c209ce2e5aaUnauthorized ", 401)
}

func (o *Nr5ade55bdd5b81c209ce2e5aaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade55bdd5b81c209ce2e5aaForbidden creates a Nr5ade55bdd5b81c209ce2e5aaForbidden with default headers values
func NewNr5ade55bdd5b81c209ce2e5aaForbidden() *Nr5ade55bdd5b81c209ce2e5aaForbidden {
	return &Nr5ade55bdd5b81c209ce2e5aaForbidden{}
}

/*Nr5ade55bdd5b81c209ce2e5aaForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5ade55bdd5b81c209ce2e5aaForbidden struct {
}

func (o *Nr5ade55bdd5b81c209ce2e5aaForbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}][%d] 5ade55bdd5b81c209ce2e5aaForbidden ", 403)
}

func (o *Nr5ade55bdd5b81c209ce2e5aaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade55bdd5b81c209ce2e5aaTooManyRequests creates a Nr5ade55bdd5b81c209ce2e5aaTooManyRequests with default headers values
func NewNr5ade55bdd5b81c209ce2e5aaTooManyRequests() *Nr5ade55bdd5b81c209ce2e5aaTooManyRequests {
	return &Nr5ade55bdd5b81c209ce2e5aaTooManyRequests{}
}

/*Nr5ade55bdd5b81c209ce2e5aaTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5ade55bdd5b81c209ce2e5aaTooManyRequests struct {
}

func (o *Nr5ade55bdd5b81c209ce2e5aaTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}][%d] 5ade55bdd5b81c209ce2e5aaTooManyRequests ", 429)
}

func (o *Nr5ade55bdd5b81c209ce2e5aaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
