// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/crazedpeanut/go-luis-authoring-client/models"
)

// NewAddListEntityParams creates a new AddListEntityParams object
// with the default values initialized.
func NewAddListEntityParams() *AddListEntityParams {
	var ()
	return &AddListEntityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddListEntityParamsWithTimeout creates a new AddListEntityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddListEntityParamsWithTimeout(timeout time.Duration) *AddListEntityParams {
	var ()
	return &AddListEntityParams{

		timeout: timeout,
	}
}

// NewAddListEntityParamsWithContext creates a new AddListEntityParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddListEntityParamsWithContext(ctx context.Context) *AddListEntityParams {
	var ()
	return &AddListEntityParams{

		Context: ctx,
	}
}

// NewAddListEntityParamsWithHTTPClient creates a new AddListEntityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddListEntityParamsWithHTTPClient(client *http.Client) *AddListEntityParams {
	var ()
	return &AddListEntityParams{
		HTTPClient: client,
	}
}

/*AddListEntityParams contains all the parameters to send to the API endpoint
for the add list entity operation typically these are written to a http.Request
*/
type AddListEntityParams struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*ClosedListModelCreateObject
	  A model object containing the name and words for the new closed list entity extractor.

	The name of the entity must be unique in the application and must not be used by a prebuilt entity.

	*/
	ClosedListModelCreateObject *models.ClosedListModelCreateObject
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add list entity params
func (o *AddListEntityParams) WithTimeout(timeout time.Duration) *AddListEntityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add list entity params
func (o *AddListEntityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add list entity params
func (o *AddListEntityParams) WithContext(ctx context.Context) *AddListEntityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add list entity params
func (o *AddListEntityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add list entity params
func (o *AddListEntityParams) WithHTTPClient(client *http.Client) *AddListEntityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add list entity params
func (o *AddListEntityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the add list entity params
func (o *AddListEntityParams) WithAppID(appID string) *AddListEntityParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the add list entity params
func (o *AddListEntityParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithClosedListModelCreateObject adds the closedListModelCreateObject to the add list entity params
func (o *AddListEntityParams) WithClosedListModelCreateObject(closedListModelCreateObject *models.ClosedListModelCreateObject) *AddListEntityParams {
	o.SetClosedListModelCreateObject(closedListModelCreateObject)
	return o
}

// SetClosedListModelCreateObject adds the closedListModelCreateObject to the add list entity params
func (o *AddListEntityParams) SetClosedListModelCreateObject(closedListModelCreateObject *models.ClosedListModelCreateObject) {
	o.ClosedListModelCreateObject = closedListModelCreateObject
}

// WithVersionID adds the versionID to the add list entity params
func (o *AddListEntityParams) WithVersionID(versionID string) *AddListEntityParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the add list entity params
func (o *AddListEntityParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *AddListEntityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.ClosedListModelCreateObject != nil {
		if err := r.SetBodyParam(o.ClosedListModelCreateObject); err != nil {
			return err
		}
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
