// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AddListReader is a Reader for the AddList structure.
type AddListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddListCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddListForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewAddListTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddListCreated creates a AddListCreated with default headers values
func NewAddListCreated() *AddListCreated {
	return &AddListCreated{}
}

/*AddListCreated handles this case with default header values.

The id of the newly created list
*/
type AddListCreated struct {
}

func (o *AddListCreated) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}/sublists][%d] addListCreated ", 201)
}

func (o *AddListCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddListBadRequest creates a AddListBadRequest with default headers values
func NewAddListBadRequest() *AddListBadRequest {
	return &AddListBadRequest{}
}

/*AddListBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.
*/
type AddListBadRequest struct {
}

func (o *AddListBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}/sublists][%d] addListBadRequest ", 400)
}

func (o *AddListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddListUnauthorized creates a AddListUnauthorized with default headers values
func NewAddListUnauthorized() *AddListUnauthorized {
	return &AddListUnauthorized{}
}

/*AddListUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type AddListUnauthorized struct {
}

func (o *AddListUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}/sublists][%d] addListUnauthorized ", 401)
}

func (o *AddListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddListForbidden creates a AddListForbidden with default headers values
func NewAddListForbidden() *AddListForbidden {
	return &AddListForbidden{}
}

/*AddListForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type AddListForbidden struct {
}

func (o *AddListForbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}/sublists][%d] addListForbidden ", 403)
}

func (o *AddListForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddListTooManyRequests creates a AddListTooManyRequests with default headers values
func NewAddListTooManyRequests() *AddListTooManyRequests {
	return &AddListTooManyRequests{}
}

/*AddListTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type AddListTooManyRequests struct {
}

func (o *AddListTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}/sublists][%d] addListTooManyRequests ", 429)
}

func (o *AddListTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
