// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/crazedpeanut/go-luis-authoring-client/models"
)

// NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParams creates a new AppsMoveAppToAnotherLuisAuthoringAzureResourceParams object
// with the default values initialized.
func NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParams() *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	var ()
	return &AppsMoveAppToAnotherLuisAuthoringAzureResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParamsWithTimeout creates a new AppsMoveAppToAnotherLuisAuthoringAzureResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParamsWithTimeout(timeout time.Duration) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	var ()
	return &AppsMoveAppToAnotherLuisAuthoringAzureResourceParams{

		timeout: timeout,
	}
}

// NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParamsWithContext creates a new AppsMoveAppToAnotherLuisAuthoringAzureResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParamsWithContext(ctx context.Context) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	var ()
	return &AppsMoveAppToAnotherLuisAuthoringAzureResourceParams{

		Context: ctx,
	}
}

// NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParamsWithHTTPClient creates a new AppsMoveAppToAnotherLuisAuthoringAzureResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAppsMoveAppToAnotherLuisAuthoringAzureResourceParamsWithHTTPClient(client *http.Client) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	var ()
	return &AppsMoveAppToAnotherLuisAuthoringAzureResourceParams{
		HTTPClient: client,
	}
}

/*AppsMoveAppToAnotherLuisAuthoringAzureResourceParams contains all the parameters to send to the API endpoint
for the apps move app to another luis authoring azure resource operation typically these are written to a http.Request
*/
type AppsMoveAppToAnotherLuisAuthoringAzureResourceParams struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*AzureAccountInfoObject
	  The azure account information object.

	*/
	AzureAccountInfoObject *models.AzureAccountInfoObject

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) WithTimeout(timeout time.Duration) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) WithContext(ctx context.Context) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) WithHTTPClient(client *http.Client) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) WithAppID(appID string) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithAzureAccountInfoObject adds the azureAccountInfoObject to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) WithAzureAccountInfoObject(azureAccountInfoObject *models.AzureAccountInfoObject) *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams {
	o.SetAzureAccountInfoObject(azureAccountInfoObject)
	return o
}

// SetAzureAccountInfoObject adds the azureAccountInfoObject to the apps move app to another luis authoring azure resource params
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) SetAzureAccountInfoObject(azureAccountInfoObject *models.AzureAccountInfoObject) {
	o.AzureAccountInfoObject = azureAccountInfoObject
}

// WriteToRequest writes these params to a swagger request
func (o *AppsMoveAppToAnotherLuisAuthoringAzureResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.AzureAccountInfoObject != nil {
		if err := r.SetBodyParam(o.AzureAccountInfoObject); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
