// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteClosedListReader is a Reader for the DeleteClosedList structure.
type DeleteClosedListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClosedListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteClosedListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteClosedListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteClosedListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteClosedListForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteClosedListTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteClosedListOK creates a DeleteClosedListOK with default headers values
func NewDeleteClosedListOK() *DeleteClosedListOK {
	return &DeleteClosedListOK{}
}

/*DeleteClosedListOK handles this case with default header values.

DeleteClosedListOK delete closed list o k
*/
type DeleteClosedListOK struct {
}

func (o *DeleteClosedListOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}][%d] deleteClosedListOK ", 200)
}

func (o *DeleteClosedListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClosedListBadRequest creates a DeleteClosedListBadRequest with default headers values
func NewDeleteClosedListBadRequest() *DeleteClosedListBadRequest {
	return &DeleteClosedListBadRequest{}
}

/*DeleteClosedListBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing or malformed.
*/
type DeleteClosedListBadRequest struct {
}

func (o *DeleteClosedListBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}][%d] deleteClosedListBadRequest ", 400)
}

func (o *DeleteClosedListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClosedListUnauthorized creates a DeleteClosedListUnauthorized with default headers values
func NewDeleteClosedListUnauthorized() *DeleteClosedListUnauthorized {
	return &DeleteClosedListUnauthorized{}
}

/*DeleteClosedListUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type DeleteClosedListUnauthorized struct {
}

func (o *DeleteClosedListUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}][%d] deleteClosedListUnauthorized ", 401)
}

func (o *DeleteClosedListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClosedListForbidden creates a DeleteClosedListForbidden with default headers values
func NewDeleteClosedListForbidden() *DeleteClosedListForbidden {
	return &DeleteClosedListForbidden{}
}

/*DeleteClosedListForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type DeleteClosedListForbidden struct {
}

func (o *DeleteClosedListForbidden) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}][%d] deleteClosedListForbidden ", 403)
}

func (o *DeleteClosedListForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClosedListTooManyRequests creates a DeleteClosedListTooManyRequests with default headers values
func NewDeleteClosedListTooManyRequests() *DeleteClosedListTooManyRequests {
	return &DeleteClosedListTooManyRequests{}
}

/*DeleteClosedListTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type DeleteClosedListTooManyRequests struct {
}

func (o *DeleteClosedListTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/closedlists/{clEntityId}][%d] deleteClosedListTooManyRequests ", 429)
}

func (o *DeleteClosedListTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
