// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetApplicationsParams creates a new GetApplicationsParams object
// with the default values initialized.
func NewGetApplicationsParams() *GetApplicationsParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &GetApplicationsParams{
		Skip: &skipDefault,
		Take: &takeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationsParamsWithTimeout creates a new GetApplicationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationsParamsWithTimeout(timeout time.Duration) *GetApplicationsParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &GetApplicationsParams{
		Skip: &skipDefault,
		Take: &takeDefault,

		timeout: timeout,
	}
}

// NewGetApplicationsParamsWithContext creates a new GetApplicationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationsParamsWithContext(ctx context.Context) *GetApplicationsParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &GetApplicationsParams{
		Skip: &skipDefault,
		Take: &takeDefault,

		Context: ctx,
	}
}

// NewGetApplicationsParamsWithHTTPClient creates a new GetApplicationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationsParamsWithHTTPClient(client *http.Client) *GetApplicationsParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &GetApplicationsParams{
		Skip:       &skipDefault,
		Take:       &takeDefault,
		HTTPClient: client,
	}
}

/*GetApplicationsParams contains all the parameters to send to the API endpoint
for the get applications operation typically these are written to a http.Request
*/
type GetApplicationsParams struct {

	/*Skip
	  The number of entries to skip. Default value is 0.

	*/
	Skip *int64
	/*Take
	  The number of entries to return. Maximum page size is 500. Default is 100.

	*/
	Take *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get applications params
func (o *GetApplicationsParams) WithTimeout(timeout time.Duration) *GetApplicationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get applications params
func (o *GetApplicationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get applications params
func (o *GetApplicationsParams) WithContext(ctx context.Context) *GetApplicationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get applications params
func (o *GetApplicationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get applications params
func (o *GetApplicationsParams) WithHTTPClient(client *http.Client) *GetApplicationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get applications params
func (o *GetApplicationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSkip adds the skip to the get applications params
func (o *GetApplicationsParams) WithSkip(skip *int64) *GetApplicationsParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the get applications params
func (o *GetApplicationsParams) SetSkip(skip *int64) {
	o.Skip = skip
}

// WithTake adds the take to the get applications params
func (o *GetApplicationsParams) WithTake(take *int64) *GetApplicationsParams {
	o.SetTake(take)
	return o
}

// SetTake adds the take to the get applications params
func (o *GetApplicationsParams) SetTake(take *int64) {
	o.Take = take
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Skip != nil {

		// query param skip
		var qrSkip int64
		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt64(qrSkip)
		if qSkip != "" {
			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}

	}

	if o.Take != nil {

		// query param take
		var qrTake int64
		if o.Take != nil {
			qrTake = *o.Take
		}
		qTake := swag.FormatInt64(qrTake)
		if qTake != "" {
			if err := r.SetQueryParam("take", qTake); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
