// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/crazedpeanut/go-luis-authoring-client/models"
)

// GetApplicationVersionReader is a Reader for the GetApplicationVersion structure.
type GetApplicationVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApplicationVersionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetApplicationVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetApplicationVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetApplicationVersionTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApplicationVersionOK creates a GetApplicationVersionOK with default headers values
func NewGetApplicationVersionOK() *GetApplicationVersionOK {
	return &GetApplicationVersionOK{}
}

/*GetApplicationVersionOK handles this case with default header values.

A JSON object containing the task info. **trainingStatus** can have the values

* NeedsTraining
* InProgress
* Trained
*/
type GetApplicationVersionOK struct {
	Payload *models.GetVersionObject
}

func (o *GetApplicationVersionOK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/][%d] getApplicationVersionOK  %+v", 200, o.Payload)
}

func (o *GetApplicationVersionOK) GetPayload() *models.GetVersionObject {
	return o.Payload
}

func (o *GetApplicationVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetVersionObject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationVersionBadRequest creates a GetApplicationVersionBadRequest with default headers values
func NewGetApplicationVersionBadRequest() *GetApplicationVersionBadRequest {
	return &GetApplicationVersionBadRequest{}
}

/*GetApplicationVersionBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type GetApplicationVersionBadRequest struct {
}

func (o *GetApplicationVersionBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/][%d] getApplicationVersionBadRequest ", 400)
}

func (o *GetApplicationVersionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationVersionUnauthorized creates a GetApplicationVersionUnauthorized with default headers values
func NewGetApplicationVersionUnauthorized() *GetApplicationVersionUnauthorized {
	return &GetApplicationVersionUnauthorized{}
}

/*GetApplicationVersionUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type GetApplicationVersionUnauthorized struct {
}

func (o *GetApplicationVersionUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/][%d] getApplicationVersionUnauthorized ", 401)
}

func (o *GetApplicationVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationVersionForbidden creates a GetApplicationVersionForbidden with default headers values
func NewGetApplicationVersionForbidden() *GetApplicationVersionForbidden {
	return &GetApplicationVersionForbidden{}
}

/*GetApplicationVersionForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type GetApplicationVersionForbidden struct {
}

func (o *GetApplicationVersionForbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/][%d] getApplicationVersionForbidden ", 403)
}

func (o *GetApplicationVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationVersionTooManyRequests creates a GetApplicationVersionTooManyRequests with default headers values
func NewGetApplicationVersionTooManyRequests() *GetApplicationVersionTooManyRequests {
	return &GetApplicationVersionTooManyRequests{}
}

/*GetApplicationVersionTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type GetApplicationVersionTooManyRequests struct {
}

func (o *GetApplicationVersionTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/][%d] getApplicationVersionTooManyRequests ", 429)
}

func (o *GetApplicationVersionTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
