// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewModelsGetModelExamplesListParams creates a new ModelsGetModelExamplesListParams object
// with the default values initialized.
func NewModelsGetModelExamplesListParams() *ModelsGetModelExamplesListParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &ModelsGetModelExamplesListParams{
		Skip: &skipDefault,
		Take: &takeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewModelsGetModelExamplesListParamsWithTimeout creates a new ModelsGetModelExamplesListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModelsGetModelExamplesListParamsWithTimeout(timeout time.Duration) *ModelsGetModelExamplesListParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &ModelsGetModelExamplesListParams{
		Skip: &skipDefault,
		Take: &takeDefault,

		timeout: timeout,
	}
}

// NewModelsGetModelExamplesListParamsWithContext creates a new ModelsGetModelExamplesListParams object
// with the default values initialized, and the ability to set a context for a request
func NewModelsGetModelExamplesListParamsWithContext(ctx context.Context) *ModelsGetModelExamplesListParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &ModelsGetModelExamplesListParams{
		Skip: &skipDefault,
		Take: &takeDefault,

		Context: ctx,
	}
}

// NewModelsGetModelExamplesListParamsWithHTTPClient creates a new ModelsGetModelExamplesListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModelsGetModelExamplesListParamsWithHTTPClient(client *http.Client) *ModelsGetModelExamplesListParams {
	var (
		skipDefault = int64(0)
		takeDefault = int64(100)
	)
	return &ModelsGetModelExamplesListParams{
		Skip:       &skipDefault,
		Take:       &takeDefault,
		HTTPClient: client,
	}
}

/*ModelsGetModelExamplesListParams contains all the parameters to send to the API endpoint
for the models get model examples list operation typically these are written to a http.Request
*/
type ModelsGetModelExamplesListParams struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*ModelID
	  Format - guid. The model ID.

	*/
	ModelID string
	/*Skip
	  The number of entries to skip. Default value is 0.

	*/
	Skip *int64
	/*Take
	  The number of entries to return. Maximum page size is 500. Default is 100.

	*/
	Take *int64
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithTimeout(timeout time.Duration) *ModelsGetModelExamplesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithContext(ctx context.Context) *ModelsGetModelExamplesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithHTTPClient(client *http.Client) *ModelsGetModelExamplesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithAppID(appID string) *ModelsGetModelExamplesListParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithModelID adds the modelID to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithModelID(modelID string) *ModelsGetModelExamplesListParams {
	o.SetModelID(modelID)
	return o
}

// SetModelID adds the modelId to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetModelID(modelID string) {
	o.ModelID = modelID
}

// WithSkip adds the skip to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithSkip(skip *int64) *ModelsGetModelExamplesListParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetSkip(skip *int64) {
	o.Skip = skip
}

// WithTake adds the take to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithTake(take *int64) *ModelsGetModelExamplesListParams {
	o.SetTake(take)
	return o
}

// SetTake adds the take to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetTake(take *int64) {
	o.Take = take
}

// WithVersionID adds the versionID to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) WithVersionID(versionID string) *ModelsGetModelExamplesListParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the models get model examples list params
func (o *ModelsGetModelExamplesListParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *ModelsGetModelExamplesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	// path param modelId
	if err := r.SetPathParam("modelId", o.ModelID); err != nil {
		return err
	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int64
		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt64(qrSkip)
		if qSkip != "" {
			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}

	}

	if o.Take != nil {

		// query param take
		var qrTake int64
		if o.Take != nil {
			qrTake = *o.Take
		}
		qTake := swag.FormatInt64(qrTake)
		if qTake != "" {
			if err := r.SetQueryParam("take", qTake); err != nil {
				return err
			}
		}

	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
