// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr58fcce825aca2f08a4104344Params creates a new Nr58fcce825aca2f08a4104344Params object
// with the default values initialized.
func NewNr58fcce825aca2f08a4104344Params() *Nr58fcce825aca2f08a4104344Params {
	var ()
	return &Nr58fcce825aca2f08a4104344Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr58fcce825aca2f08a4104344ParamsWithTimeout creates a new Nr58fcce825aca2f08a4104344Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr58fcce825aca2f08a4104344ParamsWithTimeout(timeout time.Duration) *Nr58fcce825aca2f08a4104344Params {
	var ()
	return &Nr58fcce825aca2f08a4104344Params{

		timeout: timeout,
	}
}

// NewNr58fcce825aca2f08a4104344ParamsWithContext creates a new Nr58fcce825aca2f08a4104344Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr58fcce825aca2f08a4104344ParamsWithContext(ctx context.Context) *Nr58fcce825aca2f08a4104344Params {
	var ()
	return &Nr58fcce825aca2f08a4104344Params{

		Context: ctx,
	}
}

// NewNr58fcce825aca2f08a4104344ParamsWithHTTPClient creates a new Nr58fcce825aca2f08a4104344Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr58fcce825aca2f08a4104344ParamsWithHTTPClient(client *http.Client) *Nr58fcce825aca2f08a4104344Params {
	var ()
	return &Nr58fcce825aca2f08a4104344Params{
		HTTPClient: client,
	}
}

/*Nr58fcce825aca2f08a4104344Params contains all the parameters to send to the API endpoint
for the 58fcce825aca2f08a4104344 operation typically these are written to a http.Request
*/
type Nr58fcce825aca2f08a4104344Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*Body
	  A JSON object containing a list of user's email addresses.


	*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) WithTimeout(timeout time.Duration) *Nr58fcce825aca2f08a4104344Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) WithContext(ctx context.Context) *Nr58fcce825aca2f08a4104344Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) WithHTTPClient(client *http.Client) *Nr58fcce825aca2f08a4104344Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) WithAppID(appID string) *Nr58fcce825aca2f08a4104344Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithBody adds the body to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) WithBody(body interface{}) *Nr58fcce825aca2f08a4104344Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the 58fcce825aca2f08a4104344 params
func (o *Nr58fcce825aca2f08a4104344Params) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *Nr58fcce825aca2f08a4104344Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
