// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c1bReader is a Reader for the Nr5890b47c39e2bb052c5b9c1b structure.
type Nr5890b47c39e2bb052c5b9c1bReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c1bReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5890b47c39e2bb052c5b9c1bOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c1bBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c1bUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c1bForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c1bTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c1bOK creates a Nr5890b47c39e2bb052c5b9c1bOK with default headers values
func NewNr5890b47c39e2bb052c5b9c1bOK() *Nr5890b47c39e2bb052c5b9c1bOK {
	return &Nr5890b47c39e2bb052c5b9c1bOK{}
}

/*Nr5890b47c39e2bb052c5b9c1bOK handles this case with default header values.

Nr5890b47c39e2bb052c5b9c1bOK 5890b47c39e2bb052c5b9c1b o k
*/
type Nr5890b47c39e2bb052c5b9c1bOK struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1bOK) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/intents/{intentId}][%d] 5890b47c39e2bb052c5b9c1bOK ", 200)
}

func (o *Nr5890b47c39e2bb052c5b9c1bOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1bBadRequest creates a Nr5890b47c39e2bb052c5b9c1bBadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c1bBadRequest() *Nr5890b47c39e2bb052c5b9c1bBadRequest {
	return &Nr5890b47c39e2bb052c5b9c1bBadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c1bBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.
*/
type Nr5890b47c39e2bb052c5b9c1bBadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1bBadRequest) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/intents/{intentId}][%d] 5890b47c39e2bb052c5b9c1bBadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c1bBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1bUnauthorized creates a Nr5890b47c39e2bb052c5b9c1bUnauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c1bUnauthorized() *Nr5890b47c39e2bb052c5b9c1bUnauthorized {
	return &Nr5890b47c39e2bb052c5b9c1bUnauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c1bUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5890b47c39e2bb052c5b9c1bUnauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1bUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/intents/{intentId}][%d] 5890b47c39e2bb052c5b9c1bUnauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c1bUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1bForbidden creates a Nr5890b47c39e2bb052c5b9c1bForbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c1bForbidden() *Nr5890b47c39e2bb052c5b9c1bForbidden {
	return &Nr5890b47c39e2bb052c5b9c1bForbidden{}
}

/*Nr5890b47c39e2bb052c5b9c1bForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c1bForbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1bForbidden) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/intents/{intentId}][%d] 5890b47c39e2bb052c5b9c1bForbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c1bForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1bTooManyRequests creates a Nr5890b47c39e2bb052c5b9c1bTooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c1bTooManyRequests() *Nr5890b47c39e2bb052c5b9c1bTooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c1bTooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c1bTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c1bTooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1bTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/intents/{intentId}][%d] 5890b47c39e2bb052c5b9c1bTooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c1bTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
