// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr5890b47c39e2bb052c5b9c22Params creates a new Nr5890b47c39e2bb052c5b9c22Params object
// with the default values initialized.
func NewNr5890b47c39e2bb052c5b9c22Params() *Nr5890b47c39e2bb052c5b9c22Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c22Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c22ParamsWithTimeout creates a new Nr5890b47c39e2bb052c5b9c22Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5890b47c39e2bb052c5b9c22ParamsWithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c22Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c22Params{

		timeout: timeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c22ParamsWithContext creates a new Nr5890b47c39e2bb052c5b9c22Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5890b47c39e2bb052c5b9c22ParamsWithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c22Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c22Params{

		Context: ctx,
	}
}

// NewNr5890b47c39e2bb052c5b9c22ParamsWithHTTPClient creates a new Nr5890b47c39e2bb052c5b9c22Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5890b47c39e2bb052c5b9c22ParamsWithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c22Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c22Params{
		HTTPClient: client,
	}
}

/*Nr5890b47c39e2bb052c5b9c22Params contains all the parameters to send to the API endpoint
for the 5890b47c39e2bb052c5b9c22 operation typically these are written to a http.Request
*/
type Nr5890b47c39e2bb052c5b9c22Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*HEntityID
	  Format - guid. The hierarchical entity extractor ID.

	*/
	HEntityID string
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) WithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c22Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) WithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c22Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) WithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c22Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) WithAppID(appID string) *Nr5890b47c39e2bb052c5b9c22Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithHEntityID adds the hEntityID to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) WithHEntityID(hEntityID string) *Nr5890b47c39e2bb052c5b9c22Params {
	o.SetHEntityID(hEntityID)
	return o
}

// SetHEntityID adds the hEntityId to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) SetHEntityID(hEntityID string) {
	o.HEntityID = hEntityID
}

// WithVersionID adds the versionID to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) WithVersionID(versionID string) *Nr5890b47c39e2bb052c5b9c22Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 5890b47c39e2bb052c5b9c22 params
func (o *Nr5890b47c39e2bb052c5b9c22Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5890b47c39e2bb052c5b9c22Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	// path param hEntityId
	if err := r.SetPathParam("hEntityId", o.HEntityID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
