// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/crazedpeanut/luis/models"
)

// NewNr5890b47c39e2bb052c5b9c24Params creates a new Nr5890b47c39e2bb052c5b9c24Params object
// with the default values initialized.
func NewNr5890b47c39e2bb052c5b9c24Params() *Nr5890b47c39e2bb052c5b9c24Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c24Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c24ParamsWithTimeout creates a new Nr5890b47c39e2bb052c5b9c24Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5890b47c39e2bb052c5b9c24ParamsWithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c24Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c24Params{

		timeout: timeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c24ParamsWithContext creates a new Nr5890b47c39e2bb052c5b9c24Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5890b47c39e2bb052c5b9c24ParamsWithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c24Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c24Params{

		Context: ctx,
	}
}

// NewNr5890b47c39e2bb052c5b9c24ParamsWithHTTPClient creates a new Nr5890b47c39e2bb052c5b9c24Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5890b47c39e2bb052c5b9c24ParamsWithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c24Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c24Params{
		HTTPClient: client,
	}
}

/*Nr5890b47c39e2bb052c5b9c24Params contains all the parameters to send to the API endpoint
for the 5890b47c39e2bb052c5b9c24 operation typically these are written to a http.Request
*/
type Nr5890b47c39e2bb052c5b9c24Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*CEntityID
	  Format - guid. The composite entity extractor ID.

	*/
	CEntityID string
	/*HierarchicalModelUpdateObject
	  A model object containing the new entity extractor name and children.

	*/
	HierarchicalModelUpdateObject *models.HierarchicalModelUpdateObject
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) WithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c24Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) WithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c24Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) WithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c24Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) WithAppID(appID string) *Nr5890b47c39e2bb052c5b9c24Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithCEntityID adds the cEntityID to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) WithCEntityID(cEntityID string) *Nr5890b47c39e2bb052c5b9c24Params {
	o.SetCEntityID(cEntityID)
	return o
}

// SetCEntityID adds the cEntityId to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) SetCEntityID(cEntityID string) {
	o.CEntityID = cEntityID
}

// WithHierarchicalModelUpdateObject adds the hierarchicalModelUpdateObject to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) WithHierarchicalModelUpdateObject(hierarchicalModelUpdateObject *models.HierarchicalModelUpdateObject) *Nr5890b47c39e2bb052c5b9c24Params {
	o.SetHierarchicalModelUpdateObject(hierarchicalModelUpdateObject)
	return o
}

// SetHierarchicalModelUpdateObject adds the hierarchicalModelUpdateObject to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) SetHierarchicalModelUpdateObject(hierarchicalModelUpdateObject *models.HierarchicalModelUpdateObject) {
	o.HierarchicalModelUpdateObject = hierarchicalModelUpdateObject
}

// WithVersionID adds the versionID to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) WithVersionID(versionID string) *Nr5890b47c39e2bb052c5b9c24Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 5890b47c39e2bb052c5b9c24 params
func (o *Nr5890b47c39e2bb052c5b9c24Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5890b47c39e2bb052c5b9c24Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	// path param cEntityId
	if err := r.SetPathParam("cEntityId", o.CEntityID); err != nil {
		return err
	}

	if o.HierarchicalModelUpdateObject != nil {
		if err := r.SetBodyParam(o.HierarchicalModelUpdateObject); err != nil {
			return err
		}
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
