// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr58b6f32139e2bb139ce823c9Params creates a new Nr58b6f32139e2bb139ce823c9Params object
// with the default values initialized.
func NewNr58b6f32139e2bb139ce823c9Params() *Nr58b6f32139e2bb139ce823c9Params {
	var ()
	return &Nr58b6f32139e2bb139ce823c9Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr58b6f32139e2bb139ce823c9ParamsWithTimeout creates a new Nr58b6f32139e2bb139ce823c9Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr58b6f32139e2bb139ce823c9ParamsWithTimeout(timeout time.Duration) *Nr58b6f32139e2bb139ce823c9Params {
	var ()
	return &Nr58b6f32139e2bb139ce823c9Params{

		timeout: timeout,
	}
}

// NewNr58b6f32139e2bb139ce823c9ParamsWithContext creates a new Nr58b6f32139e2bb139ce823c9Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr58b6f32139e2bb139ce823c9ParamsWithContext(ctx context.Context) *Nr58b6f32139e2bb139ce823c9Params {
	var ()
	return &Nr58b6f32139e2bb139ce823c9Params{

		Context: ctx,
	}
}

// NewNr58b6f32139e2bb139ce823c9ParamsWithHTTPClient creates a new Nr58b6f32139e2bb139ce823c9Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr58b6f32139e2bb139ce823c9ParamsWithHTTPClient(client *http.Client) *Nr58b6f32139e2bb139ce823c9Params {
	var ()
	return &Nr58b6f32139e2bb139ce823c9Params{
		HTTPClient: client,
	}
}

/*Nr58b6f32139e2bb139ce823c9Params contains all the parameters to send to the API endpoint
for the 58b6f32139e2bb139ce823c9 operation typically these are written to a http.Request
*/
type Nr58b6f32139e2bb139ce823c9Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*Body
	  The utterance text to delete

	*/
	Body interface{}
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) WithTimeout(timeout time.Duration) *Nr58b6f32139e2bb139ce823c9Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) WithContext(ctx context.Context) *Nr58b6f32139e2bb139ce823c9Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) WithHTTPClient(client *http.Client) *Nr58b6f32139e2bb139ce823c9Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) WithAppID(appID string) *Nr58b6f32139e2bb139ce823c9Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithBody adds the body to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) WithBody(body interface{}) *Nr58b6f32139e2bb139ce823c9Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) SetBody(body interface{}) {
	o.Body = body
}

// WithVersionID adds the versionID to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) WithVersionID(versionID string) *Nr58b6f32139e2bb139ce823c9Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 58b6f32139e2bb139ce823c9 params
func (o *Nr58b6f32139e2bb139ce823c9Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr58b6f32139e2bb139ce823c9Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
