// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/crazedpeanut/luis/models"
)

// NewNr5890b47c39e2bb052c5b9c38Params creates a new Nr5890b47c39e2bb052c5b9c38Params object
// with the default values initialized.
func NewNr5890b47c39e2bb052c5b9c38Params() *Nr5890b47c39e2bb052c5b9c38Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c38Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c38ParamsWithTimeout creates a new Nr5890b47c39e2bb052c5b9c38Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5890b47c39e2bb052c5b9c38ParamsWithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c38Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c38Params{

		timeout: timeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c38ParamsWithContext creates a new Nr5890b47c39e2bb052c5b9c38Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5890b47c39e2bb052c5b9c38ParamsWithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c38Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c38Params{

		Context: ctx,
	}
}

// NewNr5890b47c39e2bb052c5b9c38ParamsWithHTTPClient creates a new Nr5890b47c39e2bb052c5b9c38Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5890b47c39e2bb052c5b9c38ParamsWithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c38Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c38Params{
		HTTPClient: client,
	}
}

/*Nr5890b47c39e2bb052c5b9c38Params contains all the parameters to send to the API endpoint
for the 5890b47c39e2bb052c5b9c38 operation typically these are written to a http.Request
*/
type Nr5890b47c39e2bb052c5b9c38Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*ApplicationUpdateObject
	  A JSON object containing Name and Description of the application.

	*/
	ApplicationUpdateObject *models.ApplicationUpdateObject

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) WithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c38Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) WithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c38Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) WithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c38Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) WithAppID(appID string) *Nr5890b47c39e2bb052c5b9c38Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithApplicationUpdateObject adds the applicationUpdateObject to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) WithApplicationUpdateObject(applicationUpdateObject *models.ApplicationUpdateObject) *Nr5890b47c39e2bb052c5b9c38Params {
	o.SetApplicationUpdateObject(applicationUpdateObject)
	return o
}

// SetApplicationUpdateObject adds the applicationUpdateObject to the 5890b47c39e2bb052c5b9c38 params
func (o *Nr5890b47c39e2bb052c5b9c38Params) SetApplicationUpdateObject(applicationUpdateObject *models.ApplicationUpdateObject) {
	o.ApplicationUpdateObject = applicationUpdateObject
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5890b47c39e2bb052c5b9c38Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.ApplicationUpdateObject != nil {
		if err := r.SetBodyParam(o.ApplicationUpdateObject); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
