// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c2dReader is a Reader for the Nr5890b47c39e2bb052c5b9c2d structure.
type Nr5890b47c39e2bb052c5b9c2dReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c2dReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5890b47c39e2bb052c5b9c2dOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c2dBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c2dUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c2dForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c2dTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c2dOK creates a Nr5890b47c39e2bb052c5b9c2dOK with default headers values
func NewNr5890b47c39e2bb052c5b9c2dOK() *Nr5890b47c39e2bb052c5b9c2dOK {
	return &Nr5890b47c39e2bb052c5b9c2dOK{}
}

/*Nr5890b47c39e2bb052c5b9c2dOK handles this case with default header values.

|Trained|Untrained|
|-----|----|
| If the active learning algorithm finds any relevant queries, they are returned with the model predictions.

If the active learning algorithm didn't find any relevant queries, an empty list is returned in the response.| Nothing is returned|
*/
type Nr5890b47c39e2bb052c5b9c2dOK struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2dOK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] 5890b47c39e2bb052c5b9c2dOK ", 200)
}

func (o *Nr5890b47c39e2bb052c5b9c2dOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2dBadRequest creates a Nr5890b47c39e2bb052c5b9c2dBadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c2dBadRequest() *Nr5890b47c39e2bb052c5b9c2dBadRequest {
	return &Nr5890b47c39e2bb052c5b9c2dBadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c2dBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5890b47c39e2bb052c5b9c2dBadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2dBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] 5890b47c39e2bb052c5b9c2dBadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c2dBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2dUnauthorized creates a Nr5890b47c39e2bb052c5b9c2dUnauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c2dUnauthorized() *Nr5890b47c39e2bb052c5b9c2dUnauthorized {
	return &Nr5890b47c39e2bb052c5b9c2dUnauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c2dUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5890b47c39e2bb052c5b9c2dUnauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2dUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] 5890b47c39e2bb052c5b9c2dUnauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c2dUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2dForbidden creates a Nr5890b47c39e2bb052c5b9c2dForbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c2dForbidden() *Nr5890b47c39e2bb052c5b9c2dForbidden {
	return &Nr5890b47c39e2bb052c5b9c2dForbidden{}
}

/*Nr5890b47c39e2bb052c5b9c2dForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c2dForbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2dForbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] 5890b47c39e2bb052c5b9c2dForbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c2dForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2dTooManyRequests creates a Nr5890b47c39e2bb052c5b9c2dTooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c2dTooManyRequests() *Nr5890b47c39e2bb052c5b9c2dTooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c2dTooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c2dTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c2dTooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2dTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] 5890b47c39e2bb052c5b9c2dTooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c2dTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
