// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr58fccccd5aca2f08a4104341Params creates a new Nr58fccccd5aca2f08a4104341Params object
// with the default values initialized.
func NewNr58fccccd5aca2f08a4104341Params() *Nr58fccccd5aca2f08a4104341Params {
	var ()
	return &Nr58fccccd5aca2f08a4104341Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr58fccccd5aca2f08a4104341ParamsWithTimeout creates a new Nr58fccccd5aca2f08a4104341Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr58fccccd5aca2f08a4104341ParamsWithTimeout(timeout time.Duration) *Nr58fccccd5aca2f08a4104341Params {
	var ()
	return &Nr58fccccd5aca2f08a4104341Params{

		timeout: timeout,
	}
}

// NewNr58fccccd5aca2f08a4104341ParamsWithContext creates a new Nr58fccccd5aca2f08a4104341Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr58fccccd5aca2f08a4104341ParamsWithContext(ctx context.Context) *Nr58fccccd5aca2f08a4104341Params {
	var ()
	return &Nr58fccccd5aca2f08a4104341Params{

		Context: ctx,
	}
}

// NewNr58fccccd5aca2f08a4104341ParamsWithHTTPClient creates a new Nr58fccccd5aca2f08a4104341Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr58fccccd5aca2f08a4104341ParamsWithHTTPClient(client *http.Client) *Nr58fccccd5aca2f08a4104341Params {
	var ()
	return &Nr58fccccd5aca2f08a4104341Params{
		HTTPClient: client,
	}
}

/*Nr58fccccd5aca2f08a4104341Params contains all the parameters to send to the API endpoint
for the 58fccccd5aca2f08a4104341 operation typically these are written to a http.Request
*/
type Nr58fccccd5aca2f08a4104341Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) WithTimeout(timeout time.Duration) *Nr58fccccd5aca2f08a4104341Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) WithContext(ctx context.Context) *Nr58fccccd5aca2f08a4104341Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) WithHTTPClient(client *http.Client) *Nr58fccccd5aca2f08a4104341Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) WithAppID(appID string) *Nr58fccccd5aca2f08a4104341Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 58fccccd5aca2f08a4104341 params
func (o *Nr58fccccd5aca2f08a4104341Params) SetAppID(appID string) {
	o.AppID = appID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr58fccccd5aca2f08a4104341Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
