// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c06Reader is a Reader for the Nr5890b47c39e2bb052c5b9c06 structure.
type Nr5890b47c39e2bb052c5b9c06Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c06Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5890b47c39e2bb052c5b9c06OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c06BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c06Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c06Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c06TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c06OK creates a Nr5890b47c39e2bb052c5b9c06OK with default headers values
func NewNr5890b47c39e2bb052c5b9c06OK() *Nr5890b47c39e2bb052c5b9c06OK {
	return &Nr5890b47c39e2bb052c5b9c06OK{}
}

/*Nr5890b47c39e2bb052c5b9c06OK handles this case with default header values.

Nr5890b47c39e2bb052c5b9c06OK 5890b47c39e2bb052c5b9c06 o k
*/
type Nr5890b47c39e2bb052c5b9c06OK struct {
}

func (o *Nr5890b47c39e2bb052c5b9c06OK) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/phraselists/{phraselistId}][%d] 5890b47c39e2bb052c5b9c06OK ", 200)
}

func (o *Nr5890b47c39e2bb052c5b9c06OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c06BadRequest creates a Nr5890b47c39e2bb052c5b9c06BadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c06BadRequest() *Nr5890b47c39e2bb052c5b9c06BadRequest {
	return &Nr5890b47c39e2bb052c5b9c06BadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c06BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.
*/
type Nr5890b47c39e2bb052c5b9c06BadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c06BadRequest) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/phraselists/{phraselistId}][%d] 5890b47c39e2bb052c5b9c06BadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c06BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c06Unauthorized creates a Nr5890b47c39e2bb052c5b9c06Unauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c06Unauthorized() *Nr5890b47c39e2bb052c5b9c06Unauthorized {
	return &Nr5890b47c39e2bb052c5b9c06Unauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c06Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5890b47c39e2bb052c5b9c06Unauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c06Unauthorized) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/phraselists/{phraselistId}][%d] 5890b47c39e2bb052c5b9c06Unauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c06Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c06Forbidden creates a Nr5890b47c39e2bb052c5b9c06Forbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c06Forbidden() *Nr5890b47c39e2bb052c5b9c06Forbidden {
	return &Nr5890b47c39e2bb052c5b9c06Forbidden{}
}

/*Nr5890b47c39e2bb052c5b9c06Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c06Forbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c06Forbidden) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/phraselists/{phraselistId}][%d] 5890b47c39e2bb052c5b9c06Forbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c06Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c06TooManyRequests creates a Nr5890b47c39e2bb052c5b9c06TooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c06TooManyRequests() *Nr5890b47c39e2bb052c5b9c06TooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c06TooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c06TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c06TooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c06TooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/phraselists/{phraselistId}][%d] 5890b47c39e2bb052c5b9c06TooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c06TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
