// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c22Reader is a Reader for the Nr5890b47c39e2bb052c5b9c22 structure.
type Nr5890b47c39e2bb052c5b9c22Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c22Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5890b47c39e2bb052c5b9c22OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c22BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c22Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c22Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c22TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c22OK creates a Nr5890b47c39e2bb052c5b9c22OK with default headers values
func NewNr5890b47c39e2bb052c5b9c22OK() *Nr5890b47c39e2bb052c5b9c22OK {
	return &Nr5890b47c39e2bb052c5b9c22OK{}
}

/*Nr5890b47c39e2bb052c5b9c22OK handles this case with default header values.

Nr5890b47c39e2bb052c5b9c22OK 5890b47c39e2bb052c5b9c22 o k
*/
type Nr5890b47c39e2bb052c5b9c22OK struct {
}

func (o *Nr5890b47c39e2bb052c5b9c22OK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}][%d] 5890b47c39e2bb052c5b9c22OK ", 200)
}

func (o *Nr5890b47c39e2bb052c5b9c22OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c22BadRequest creates a Nr5890b47c39e2bb052c5b9c22BadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c22BadRequest() *Nr5890b47c39e2bb052c5b9c22BadRequest {
	return &Nr5890b47c39e2bb052c5b9c22BadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c22BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing or malformed.
*/
type Nr5890b47c39e2bb052c5b9c22BadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c22BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}][%d] 5890b47c39e2bb052c5b9c22BadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c22BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c22Unauthorized creates a Nr5890b47c39e2bb052c5b9c22Unauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c22Unauthorized() *Nr5890b47c39e2bb052c5b9c22Unauthorized {
	return &Nr5890b47c39e2bb052c5b9c22Unauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c22Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5890b47c39e2bb052c5b9c22Unauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c22Unauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}][%d] 5890b47c39e2bb052c5b9c22Unauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c22Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c22Forbidden creates a Nr5890b47c39e2bb052c5b9c22Forbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c22Forbidden() *Nr5890b47c39e2bb052c5b9c22Forbidden {
	return &Nr5890b47c39e2bb052c5b9c22Forbidden{}
}

/*Nr5890b47c39e2bb052c5b9c22Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c22Forbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c22Forbidden) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}][%d] 5890b47c39e2bb052c5b9c22Forbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c22Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c22TooManyRequests creates a Nr5890b47c39e2bb052c5b9c22TooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c22TooManyRequests() *Nr5890b47c39e2bb052c5b9c22TooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c22TooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c22TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c22TooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c22TooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/hierarchicalentities/{hEntityId}][%d] 5890b47c39e2bb052c5b9c22TooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c22TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
