// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr5890b47c39e2bb052c5b9c37Params creates a new Nr5890b47c39e2bb052c5b9c37Params object
// with the default values initialized.
func NewNr5890b47c39e2bb052c5b9c37Params() *Nr5890b47c39e2bb052c5b9c37Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c37Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c37ParamsWithTimeout creates a new Nr5890b47c39e2bb052c5b9c37Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5890b47c39e2bb052c5b9c37ParamsWithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c37Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c37Params{

		timeout: timeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c37ParamsWithContext creates a new Nr5890b47c39e2bb052c5b9c37Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5890b47c39e2bb052c5b9c37ParamsWithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c37Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c37Params{

		Context: ctx,
	}
}

// NewNr5890b47c39e2bb052c5b9c37ParamsWithHTTPClient creates a new Nr5890b47c39e2bb052c5b9c37Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5890b47c39e2bb052c5b9c37ParamsWithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c37Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c37Params{
		HTTPClient: client,
	}
}

/*Nr5890b47c39e2bb052c5b9c37Params contains all the parameters to send to the API endpoint
for the 5890b47c39e2bb052c5b9c37 operation typically these are written to a http.Request
*/
type Nr5890b47c39e2bb052c5b9c37Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) WithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c37Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) WithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c37Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) WithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c37Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) WithAppID(appID string) *Nr5890b47c39e2bb052c5b9c37Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5890b47c39e2bb052c5b9c37 params
func (o *Nr5890b47c39e2bb052c5b9c37Params) SetAppID(appID string) {
	o.AppID = appID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5890b47c39e2bb052c5b9c37Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
