// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c3aReader is a Reader for the Nr5890b47c39e2bb052c5b9c3a structure.
type Nr5890b47c39e2bb052c5b9c3aReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c3aReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr5890b47c39e2bb052c5b9c3aCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c3aBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c3aUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c3aForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c3aTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c3aCreated creates a Nr5890b47c39e2bb052c5b9c3aCreated with default headers values
func NewNr5890b47c39e2bb052c5b9c3aCreated() *Nr5890b47c39e2bb052c5b9c3aCreated {
	return &Nr5890b47c39e2bb052c5b9c3aCreated{}
}

/*Nr5890b47c39e2bb052c5b9c3aCreated handles this case with default header values.

The version ID of the created task.
*/
type Nr5890b47c39e2bb052c5b9c3aCreated struct {
}

func (o *Nr5890b47c39e2bb052c5b9c3aCreated) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/clone][%d] 5890b47c39e2bb052c5b9c3aCreated ", 201)
}

func (o *Nr5890b47c39e2bb052c5b9c3aCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c3aBadRequest creates a Nr5890b47c39e2bb052c5b9c3aBadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c3aBadRequest() *Nr5890b47c39e2bb052c5b9c3aBadRequest {
	return &Nr5890b47c39e2bb052c5b9c3aBadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c3aBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5890b47c39e2bb052c5b9c3aBadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c3aBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/clone][%d] 5890b47c39e2bb052c5b9c3aBadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c3aBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c3aUnauthorized creates a Nr5890b47c39e2bb052c5b9c3aUnauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c3aUnauthorized() *Nr5890b47c39e2bb052c5b9c3aUnauthorized {
	return &Nr5890b47c39e2bb052c5b9c3aUnauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c3aUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5890b47c39e2bb052c5b9c3aUnauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c3aUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/clone][%d] 5890b47c39e2bb052c5b9c3aUnauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c3aUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c3aForbidden creates a Nr5890b47c39e2bb052c5b9c3aForbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c3aForbidden() *Nr5890b47c39e2bb052c5b9c3aForbidden {
	return &Nr5890b47c39e2bb052c5b9c3aForbidden{}
}

/*Nr5890b47c39e2bb052c5b9c3aForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c3aForbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c3aForbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/clone][%d] 5890b47c39e2bb052c5b9c3aForbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c3aForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c3aTooManyRequests creates a Nr5890b47c39e2bb052c5b9c3aTooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c3aTooManyRequests() *Nr5890b47c39e2bb052c5b9c3aTooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c3aTooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c3aTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c3aTooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c3aTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/clone][%d] 5890b47c39e2bb052c5b9c3aTooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c3aTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
