// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9bffReader is a Reader for the Nr5890b47c39e2bb052c5b9bff structure.
type Nr5890b47c39e2bb052c5b9bffReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9bffReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr5890b47c39e2bb052c5b9bffCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9bffBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9bffUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9bffForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9bffTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9bffCreated creates a Nr5890b47c39e2bb052c5b9bffCreated with default headers values
func NewNr5890b47c39e2bb052c5b9bffCreated() *Nr5890b47c39e2bb052c5b9bffCreated {
	return &Nr5890b47c39e2bb052c5b9bffCreated{}
}

/*Nr5890b47c39e2bb052c5b9bffCreated handles this case with default header values.

The ID of the created feature.
*/
type Nr5890b47c39e2bb052c5b9bffCreated struct {
}

func (o *Nr5890b47c39e2bb052c5b9bffCreated) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/phraselists][%d] 5890b47c39e2bb052c5b9bffCreated ", 201)
}

func (o *Nr5890b47c39e2bb052c5b9bffCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9bffBadRequest creates a Nr5890b47c39e2bb052c5b9bffBadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9bffBadRequest() *Nr5890b47c39e2bb052c5b9bffBadRequest {
	return &Nr5890b47c39e2bb052c5b9bffBadRequest{}
}

/*Nr5890b47c39e2bb052c5b9bffBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.
*/
type Nr5890b47c39e2bb052c5b9bffBadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9bffBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/phraselists][%d] 5890b47c39e2bb052c5b9bffBadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9bffBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9bffUnauthorized creates a Nr5890b47c39e2bb052c5b9bffUnauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9bffUnauthorized() *Nr5890b47c39e2bb052c5b9bffUnauthorized {
	return &Nr5890b47c39e2bb052c5b9bffUnauthorized{}
}

/*Nr5890b47c39e2bb052c5b9bffUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5890b47c39e2bb052c5b9bffUnauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9bffUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/phraselists][%d] 5890b47c39e2bb052c5b9bffUnauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9bffUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9bffForbidden creates a Nr5890b47c39e2bb052c5b9bffForbidden with default headers values
func NewNr5890b47c39e2bb052c5b9bffForbidden() *Nr5890b47c39e2bb052c5b9bffForbidden {
	return &Nr5890b47c39e2bb052c5b9bffForbidden{}
}

/*Nr5890b47c39e2bb052c5b9bffForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9bffForbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9bffForbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/phraselists][%d] 5890b47c39e2bb052c5b9bffForbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9bffForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9bffTooManyRequests creates a Nr5890b47c39e2bb052c5b9bffTooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9bffTooManyRequests() *Nr5890b47c39e2bb052c5b9bffTooManyRequests {
	return &Nr5890b47c39e2bb052c5b9bffTooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9bffTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9bffTooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9bffTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/phraselists][%d] 5890b47c39e2bb052c5b9bffTooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9bffTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
