// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c1fReader is a Reader for the Nr5890b47c39e2bb052c5b9c1f structure.
type Nr5890b47c39e2bb052c5b9c1fReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c1fReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5890b47c39e2bb052c5b9c1fOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c1fBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c1fUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c1fForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c1fTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c1fOK creates a Nr5890b47c39e2bb052c5b9c1fOK with default headers values
func NewNr5890b47c39e2bb052c5b9c1fOK() *Nr5890b47c39e2bb052c5b9c1fOK {
	return &Nr5890b47c39e2bb052c5b9c1fOK{}
}

/*Nr5890b47c39e2bb052c5b9c1fOK handles this case with default header values.

Nr5890b47c39e2bb052c5b9c1fOK 5890b47c39e2bb052c5b9c1f o k
*/
type Nr5890b47c39e2bb052c5b9c1fOK struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1fOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/entities/{entityId}][%d] 5890b47c39e2bb052c5b9c1fOK ", 200)
}

func (o *Nr5890b47c39e2bb052c5b9c1fOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1fBadRequest creates a Nr5890b47c39e2bb052c5b9c1fBadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c1fBadRequest() *Nr5890b47c39e2bb052c5b9c1fBadRequest {
	return &Nr5890b47c39e2bb052c5b9c1fBadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c1fBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing or malformed.
*/
type Nr5890b47c39e2bb052c5b9c1fBadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1fBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/entities/{entityId}][%d] 5890b47c39e2bb052c5b9c1fBadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c1fBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1fUnauthorized creates a Nr5890b47c39e2bb052c5b9c1fUnauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c1fUnauthorized() *Nr5890b47c39e2bb052c5b9c1fUnauthorized {
	return &Nr5890b47c39e2bb052c5b9c1fUnauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c1fUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5890b47c39e2bb052c5b9c1fUnauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1fUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/entities/{entityId}][%d] 5890b47c39e2bb052c5b9c1fUnauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c1fUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1fForbidden creates a Nr5890b47c39e2bb052c5b9c1fForbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c1fForbidden() *Nr5890b47c39e2bb052c5b9c1fForbidden {
	return &Nr5890b47c39e2bb052c5b9c1fForbidden{}
}

/*Nr5890b47c39e2bb052c5b9c1fForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c1fForbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1fForbidden) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/entities/{entityId}][%d] 5890b47c39e2bb052c5b9c1fForbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c1fForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c1fTooManyRequests creates a Nr5890b47c39e2bb052c5b9c1fTooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c1fTooManyRequests() *Nr5890b47c39e2bb052c5b9c1fTooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c1fTooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c1fTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c1fTooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c1fTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/entities/{entityId}][%d] 5890b47c39e2bb052c5b9c1fTooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c1fTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
