// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c2bReader is a Reader for the Nr5890b47c39e2bb052c5b9c2b structure.
type Nr5890b47c39e2bb052c5b9c2bReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c2bReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5890b47c39e2bb052c5b9c2bOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c2bBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c2bUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c2bForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c2bTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c2bOK creates a Nr5890b47c39e2bb052c5b9c2bOK with default headers values
func NewNr5890b47c39e2bb052c5b9c2bOK() *Nr5890b47c39e2bb052c5b9c2bOK {
	return &Nr5890b47c39e2bb052c5b9c2bOK{}
}

/*Nr5890b47c39e2bb052c5b9c2bOK handles this case with default header values.

Nr5890b47c39e2bb052c5b9c2bOK 5890b47c39e2bb052c5b9c2b o k
*/
type Nr5890b47c39e2bb052c5b9c2bOK struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2bOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/prebuilts/{prebuiltId}][%d] 5890b47c39e2bb052c5b9c2bOK ", 200)
}

func (o *Nr5890b47c39e2bb052c5b9c2bOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2bBadRequest creates a Nr5890b47c39e2bb052c5b9c2bBadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c2bBadRequest() *Nr5890b47c39e2bb052c5b9c2bBadRequest {
	return &Nr5890b47c39e2bb052c5b9c2bBadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c2bBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing or malformed.
*/
type Nr5890b47c39e2bb052c5b9c2bBadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2bBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/prebuilts/{prebuiltId}][%d] 5890b47c39e2bb052c5b9c2bBadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c2bBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2bUnauthorized creates a Nr5890b47c39e2bb052c5b9c2bUnauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c2bUnauthorized() *Nr5890b47c39e2bb052c5b9c2bUnauthorized {
	return &Nr5890b47c39e2bb052c5b9c2bUnauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c2bUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5890b47c39e2bb052c5b9c2bUnauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2bUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/prebuilts/{prebuiltId}][%d] 5890b47c39e2bb052c5b9c2bUnauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c2bUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2bForbidden creates a Nr5890b47c39e2bb052c5b9c2bForbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c2bForbidden() *Nr5890b47c39e2bb052c5b9c2bForbidden {
	return &Nr5890b47c39e2bb052c5b9c2bForbidden{}
}

/*Nr5890b47c39e2bb052c5b9c2bForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c2bForbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2bForbidden) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/prebuilts/{prebuiltId}][%d] 5890b47c39e2bb052c5b9c2bForbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c2bForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c2bTooManyRequests creates a Nr5890b47c39e2bb052c5b9c2bTooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c2bTooManyRequests() *Nr5890b47c39e2bb052c5b9c2bTooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c2bTooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c2bTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c2bTooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c2bTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appId}/versions/{versionId}/prebuilts/{prebuiltId}][%d] 5890b47c39e2bb052c5b9c2bTooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c2bTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
