// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr58fccccd5aca2f08a4104341Reader is a Reader for the Nr58fccccd5aca2f08a4104341 structure.
type Nr58fccccd5aca2f08a4104341Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr58fccccd5aca2f08a4104341Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr58fccccd5aca2f08a4104341OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr58fccccd5aca2f08a4104341BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr58fccccd5aca2f08a4104341Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr58fccccd5aca2f08a4104341Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr58fccccd5aca2f08a4104341TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr58fccccd5aca2f08a4104341OK creates a Nr58fccccd5aca2f08a4104341OK with default headers values
func NewNr58fccccd5aca2f08a4104341OK() *Nr58fccccd5aca2f08a4104341OK {
	return &Nr58fccccd5aca2f08a4104341OK{}
}

/*Nr58fccccd5aca2f08a4104341OK handles this case with default header values.

The list includes a single owner. All collaborators are listed in the emails array.
*/
type Nr58fccccd5aca2f08a4104341OK struct {
}

func (o *Nr58fccccd5aca2f08a4104341OK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/permissions][%d] 58fccccd5aca2f08a4104341OK ", 200)
}

func (o *Nr58fccccd5aca2f08a4104341OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr58fccccd5aca2f08a4104341BadRequest creates a Nr58fccccd5aca2f08a4104341BadRequest with default headers values
func NewNr58fccccd5aca2f08a4104341BadRequest() *Nr58fccccd5aca2f08a4104341BadRequest {
	return &Nr58fccccd5aca2f08a4104341BadRequest{}
}

/*Nr58fccccd5aca2f08a4104341BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr58fccccd5aca2f08a4104341BadRequest struct {
}

func (o *Nr58fccccd5aca2f08a4104341BadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/permissions][%d] 58fccccd5aca2f08a4104341BadRequest ", 400)
}

func (o *Nr58fccccd5aca2f08a4104341BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr58fccccd5aca2f08a4104341Unauthorized creates a Nr58fccccd5aca2f08a4104341Unauthorized with default headers values
func NewNr58fccccd5aca2f08a4104341Unauthorized() *Nr58fccccd5aca2f08a4104341Unauthorized {
	return &Nr58fccccd5aca2f08a4104341Unauthorized{}
}

/*Nr58fccccd5aca2f08a4104341Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr58fccccd5aca2f08a4104341Unauthorized struct {
}

func (o *Nr58fccccd5aca2f08a4104341Unauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/permissions][%d] 58fccccd5aca2f08a4104341Unauthorized ", 401)
}

func (o *Nr58fccccd5aca2f08a4104341Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr58fccccd5aca2f08a4104341Forbidden creates a Nr58fccccd5aca2f08a4104341Forbidden with default headers values
func NewNr58fccccd5aca2f08a4104341Forbidden() *Nr58fccccd5aca2f08a4104341Forbidden {
	return &Nr58fccccd5aca2f08a4104341Forbidden{}
}

/*Nr58fccccd5aca2f08a4104341Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr58fccccd5aca2f08a4104341Forbidden struct {
}

func (o *Nr58fccccd5aca2f08a4104341Forbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/permissions][%d] 58fccccd5aca2f08a4104341Forbidden ", 403)
}

func (o *Nr58fccccd5aca2f08a4104341Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr58fccccd5aca2f08a4104341TooManyRequests creates a Nr58fccccd5aca2f08a4104341TooManyRequests with default headers values
func NewNr58fccccd5aca2f08a4104341TooManyRequests() *Nr58fccccd5aca2f08a4104341TooManyRequests {
	return &Nr58fccccd5aca2f08a4104341TooManyRequests{}
}

/*Nr58fccccd5aca2f08a4104341TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr58fccccd5aca2f08a4104341TooManyRequests struct {
}

func (o *Nr58fccccd5aca2f08a4104341TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/permissions][%d] 58fccccd5aca2f08a4104341TooManyRequests ", 429)
}

func (o *Nr58fccccd5aca2f08a4104341TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
