// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr5890b47c39e2bb052c5b9c36Params creates a new Nr5890b47c39e2bb052c5b9c36Params object
// with the default values initialized.
func NewNr5890b47c39e2bb052c5b9c36Params() *Nr5890b47c39e2bb052c5b9c36Params {
	var (
		includeResponseDefault = bool(true)
	)
	return &Nr5890b47c39e2bb052c5b9c36Params{
		IncludeResponse: &includeResponseDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c36ParamsWithTimeout creates a new Nr5890b47c39e2bb052c5b9c36Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5890b47c39e2bb052c5b9c36ParamsWithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c36Params {
	var (
		includeResponseDefault = bool(true)
	)
	return &Nr5890b47c39e2bb052c5b9c36Params{
		IncludeResponse: &includeResponseDefault,

		timeout: timeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c36ParamsWithContext creates a new Nr5890b47c39e2bb052c5b9c36Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5890b47c39e2bb052c5b9c36ParamsWithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c36Params {
	var (
		includeResponseDefault = bool(true)
	)
	return &Nr5890b47c39e2bb052c5b9c36Params{
		IncludeResponse: &includeResponseDefault,

		Context: ctx,
	}
}

// NewNr5890b47c39e2bb052c5b9c36ParamsWithHTTPClient creates a new Nr5890b47c39e2bb052c5b9c36Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5890b47c39e2bb052c5b9c36ParamsWithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c36Params {
	var (
		includeResponseDefault = bool(true)
	)
	return &Nr5890b47c39e2bb052c5b9c36Params{
		IncludeResponse: &includeResponseDefault,
		HTTPClient:      client,
	}
}

/*Nr5890b47c39e2bb052c5b9c36Params contains all the parameters to send to the API endpoint
for the 5890b47c39e2bb052c5b9c36 operation typically these are written to a http.Request
*/
type Nr5890b47c39e2bb052c5b9c36Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*IncludeResponse
	  indicate whether to include the response column in the csv file.

	*/
	IncludeResponse *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) WithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c36Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) WithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c36Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) WithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c36Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) WithAppID(appID string) *Nr5890b47c39e2bb052c5b9c36Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithIncludeResponse adds the includeResponse to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) WithIncludeResponse(includeResponse *bool) *Nr5890b47c39e2bb052c5b9c36Params {
	o.SetIncludeResponse(includeResponse)
	return o
}

// SetIncludeResponse adds the includeResponse to the 5890b47c39e2bb052c5b9c36 params
func (o *Nr5890b47c39e2bb052c5b9c36Params) SetIncludeResponse(includeResponse *bool) {
	o.IncludeResponse = includeResponse
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5890b47c39e2bb052c5b9c36Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.IncludeResponse != nil {

		// query param includeResponse
		var qrIncludeResponse bool
		if o.IncludeResponse != nil {
			qrIncludeResponse = *o.IncludeResponse
		}
		qIncludeResponse := swag.FormatBool(qrIncludeResponse)
		if qIncludeResponse != "" {
			if err := r.SetQueryParam("includeResponse", qIncludeResponse); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
