// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/crazedpeanut/luis/models"
)

// NewNr5890b47c39e2bb052c5b9c03Params creates a new Nr5890b47c39e2bb052c5b9c03Params object
// with the default values initialized.
func NewNr5890b47c39e2bb052c5b9c03Params() *Nr5890b47c39e2bb052c5b9c03Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c03Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c03ParamsWithTimeout creates a new Nr5890b47c39e2bb052c5b9c03Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5890b47c39e2bb052c5b9c03ParamsWithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c03Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c03Params{

		timeout: timeout,
	}
}

// NewNr5890b47c39e2bb052c5b9c03ParamsWithContext creates a new Nr5890b47c39e2bb052c5b9c03Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5890b47c39e2bb052c5b9c03ParamsWithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c03Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c03Params{

		Context: ctx,
	}
}

// NewNr5890b47c39e2bb052c5b9c03ParamsWithHTTPClient creates a new Nr5890b47c39e2bb052c5b9c03Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5890b47c39e2bb052c5b9c03ParamsWithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c03Params {
	var ()
	return &Nr5890b47c39e2bb052c5b9c03Params{
		HTTPClient: client,
	}
}

/*Nr5890b47c39e2bb052c5b9c03Params contains all the parameters to send to the API endpoint
for the 5890b47c39e2bb052c5b9c03 operation typically these are written to a http.Request
*/
type Nr5890b47c39e2bb052c5b9c03Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*PatternID
	  The ID of the feature to be updated.

	*/
	PatternID int64
	/*PatternUpdateObject
	  A JSON object with properties of one of the following examples:
	```json
	{
	    "id": 507628,
	    "name": "testPattern",
	    "pattern": "\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\b",
	    "isActive": true
	}
	```
	```json
	{"IsActive":true}
	```

	*/
	PatternUpdateObject *models.PatternUpdateObject
	/*VersionID
	  The version ID of the task.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) WithTimeout(timeout time.Duration) *Nr5890b47c39e2bb052c5b9c03Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) WithContext(ctx context.Context) *Nr5890b47c39e2bb052c5b9c03Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) WithHTTPClient(client *http.Client) *Nr5890b47c39e2bb052c5b9c03Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) WithAppID(appID string) *Nr5890b47c39e2bb052c5b9c03Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithPatternID adds the patternID to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) WithPatternID(patternID int64) *Nr5890b47c39e2bb052c5b9c03Params {
	o.SetPatternID(patternID)
	return o
}

// SetPatternID adds the patternId to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) SetPatternID(patternID int64) {
	o.PatternID = patternID
}

// WithPatternUpdateObject adds the patternUpdateObject to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) WithPatternUpdateObject(patternUpdateObject *models.PatternUpdateObject) *Nr5890b47c39e2bb052c5b9c03Params {
	o.SetPatternUpdateObject(patternUpdateObject)
	return o
}

// SetPatternUpdateObject adds the patternUpdateObject to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) SetPatternUpdateObject(patternUpdateObject *models.PatternUpdateObject) {
	o.PatternUpdateObject = patternUpdateObject
}

// WithVersionID adds the versionID to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) WithVersionID(versionID string) *Nr5890b47c39e2bb052c5b9c03Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 5890b47c39e2bb052c5b9c03 params
func (o *Nr5890b47c39e2bb052c5b9c03Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5890b47c39e2bb052c5b9c03Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	// path param patternId
	if err := r.SetPathParam("patternId", swag.FormatInt64(o.PatternID)); err != nil {
		return err
	}

	if o.PatternUpdateObject != nil {
		if err := r.SetBodyParam(o.PatternUpdateObject); err != nil {
			return err
		}
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
