// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5890b47c39e2bb052c5b9c16Reader is a Reader for the Nr5890b47c39e2bb052c5b9c16 structure.
type Nr5890b47c39e2bb052c5b9c16Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5890b47c39e2bb052c5b9c16Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr5890b47c39e2bb052c5b9c16Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5890b47c39e2bb052c5b9c16BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5890b47c39e2bb052c5b9c16Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5890b47c39e2bb052c5b9c16Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5890b47c39e2bb052c5b9c16TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5890b47c39e2bb052c5b9c16Created creates a Nr5890b47c39e2bb052c5b9c16Created with default headers values
func NewNr5890b47c39e2bb052c5b9c16Created() *Nr5890b47c39e2bb052c5b9c16Created {
	return &Nr5890b47c39e2bb052c5b9c16Created{}
}

/*Nr5890b47c39e2bb052c5b9c16Created handles this case with default header values.

An array of the created prebuilt extractor infos.
*/
type Nr5890b47c39e2bb052c5b9c16Created struct {
}

func (o *Nr5890b47c39e2bb052c5b9c16Created) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/prebuilts][%d] 5890b47c39e2bb052c5b9c16Created ", 201)
}

func (o *Nr5890b47c39e2bb052c5b9c16Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c16BadRequest creates a Nr5890b47c39e2bb052c5b9c16BadRequest with default headers values
func NewNr5890b47c39e2bb052c5b9c16BadRequest() *Nr5890b47c39e2bb052c5b9c16BadRequest {
	return &Nr5890b47c39e2bb052c5b9c16BadRequest{}
}

/*Nr5890b47c39e2bb052c5b9c16BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.
*/
type Nr5890b47c39e2bb052c5b9c16BadRequest struct {
}

func (o *Nr5890b47c39e2bb052c5b9c16BadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/prebuilts][%d] 5890b47c39e2bb052c5b9c16BadRequest ", 400)
}

func (o *Nr5890b47c39e2bb052c5b9c16BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c16Unauthorized creates a Nr5890b47c39e2bb052c5b9c16Unauthorized with default headers values
func NewNr5890b47c39e2bb052c5b9c16Unauthorized() *Nr5890b47c39e2bb052c5b9c16Unauthorized {
	return &Nr5890b47c39e2bb052c5b9c16Unauthorized{}
}

/*Nr5890b47c39e2bb052c5b9c16Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5890b47c39e2bb052c5b9c16Unauthorized struct {
}

func (o *Nr5890b47c39e2bb052c5b9c16Unauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/prebuilts][%d] 5890b47c39e2bb052c5b9c16Unauthorized ", 401)
}

func (o *Nr5890b47c39e2bb052c5b9c16Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c16Forbidden creates a Nr5890b47c39e2bb052c5b9c16Forbidden with default headers values
func NewNr5890b47c39e2bb052c5b9c16Forbidden() *Nr5890b47c39e2bb052c5b9c16Forbidden {
	return &Nr5890b47c39e2bb052c5b9c16Forbidden{}
}

/*Nr5890b47c39e2bb052c5b9c16Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5890b47c39e2bb052c5b9c16Forbidden struct {
}

func (o *Nr5890b47c39e2bb052c5b9c16Forbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/prebuilts][%d] 5890b47c39e2bb052c5b9c16Forbidden ", 403)
}

func (o *Nr5890b47c39e2bb052c5b9c16Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5890b47c39e2bb052c5b9c16TooManyRequests creates a Nr5890b47c39e2bb052c5b9c16TooManyRequests with default headers values
func NewNr5890b47c39e2bb052c5b9c16TooManyRequests() *Nr5890b47c39e2bb052c5b9c16TooManyRequests {
	return &Nr5890b47c39e2bb052c5b9c16TooManyRequests{}
}

/*Nr5890b47c39e2bb052c5b9c16TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5890b47c39e2bb052c5b9c16TooManyRequests struct {
}

func (o *Nr5890b47c39e2bb052c5b9c16TooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/prebuilts][%d] 5890b47c39e2bb052c5b9c16TooManyRequests ", 429)
}

func (o *Nr5890b47c39e2bb052c5b9c16TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
