// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr59104d855aca2f0b48c76be4Reader is a Reader for the Nr59104d855aca2f0b48c76be4 structure.
type Nr59104d855aca2f0b48c76be4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr59104d855aca2f0b48c76be4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr59104d855aca2f0b48c76be4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr59104d855aca2f0b48c76be4BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr59104d855aca2f0b48c76be4Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr59104d855aca2f0b48c76be4Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr59104d855aca2f0b48c76be4TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr59104d855aca2f0b48c76be4OK creates a Nr59104d855aca2f0b48c76be4OK with default headers values
func NewNr59104d855aca2f0b48c76be4OK() *Nr59104d855aca2f0b48c76be4OK {
	return &Nr59104d855aca2f0b48c76be4OK{}
}

/*Nr59104d855aca2f0b48c76be4OK handles this case with default header values.

Returns a list of all domains and their intents/entities representation for a specific culture
*/
type Nr59104d855aca2f0b48c76be4OK struct {
}

func (o *Nr59104d855aca2f0b48c76be4OK) Error() string {
	return fmt.Sprintf("[GET /apps/customprebuiltdomains/{culture}][%d] 59104d855aca2f0b48c76be4OK ", 200)
}

func (o *Nr59104d855aca2f0b48c76be4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr59104d855aca2f0b48c76be4BadRequest creates a Nr59104d855aca2f0b48c76be4BadRequest with default headers values
func NewNr59104d855aca2f0b48c76be4BadRequest() *Nr59104d855aca2f0b48c76be4BadRequest {
	return &Nr59104d855aca2f0b48c76be4BadRequest{}
}

/*Nr59104d855aca2f0b48c76be4BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr59104d855aca2f0b48c76be4BadRequest struct {
}

func (o *Nr59104d855aca2f0b48c76be4BadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/customprebuiltdomains/{culture}][%d] 59104d855aca2f0b48c76be4BadRequest ", 400)
}

func (o *Nr59104d855aca2f0b48c76be4BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr59104d855aca2f0b48c76be4Unauthorized creates a Nr59104d855aca2f0b48c76be4Unauthorized with default headers values
func NewNr59104d855aca2f0b48c76be4Unauthorized() *Nr59104d855aca2f0b48c76be4Unauthorized {
	return &Nr59104d855aca2f0b48c76be4Unauthorized{}
}

/*Nr59104d855aca2f0b48c76be4Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr59104d855aca2f0b48c76be4Unauthorized struct {
}

func (o *Nr59104d855aca2f0b48c76be4Unauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/customprebuiltdomains/{culture}][%d] 59104d855aca2f0b48c76be4Unauthorized ", 401)
}

func (o *Nr59104d855aca2f0b48c76be4Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr59104d855aca2f0b48c76be4Forbidden creates a Nr59104d855aca2f0b48c76be4Forbidden with default headers values
func NewNr59104d855aca2f0b48c76be4Forbidden() *Nr59104d855aca2f0b48c76be4Forbidden {
	return &Nr59104d855aca2f0b48c76be4Forbidden{}
}

/*Nr59104d855aca2f0b48c76be4Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr59104d855aca2f0b48c76be4Forbidden struct {
}

func (o *Nr59104d855aca2f0b48c76be4Forbidden) Error() string {
	return fmt.Sprintf("[GET /apps/customprebuiltdomains/{culture}][%d] 59104d855aca2f0b48c76be4Forbidden ", 403)
}

func (o *Nr59104d855aca2f0b48c76be4Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr59104d855aca2f0b48c76be4TooManyRequests creates a Nr59104d855aca2f0b48c76be4TooManyRequests with default headers values
func NewNr59104d855aca2f0b48c76be4TooManyRequests() *Nr59104d855aca2f0b48c76be4TooManyRequests {
	return &Nr59104d855aca2f0b48c76be4TooManyRequests{}
}

/*Nr59104d855aca2f0b48c76be4TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr59104d855aca2f0b48c76be4TooManyRequests struct {
}

func (o *Nr59104d855aca2f0b48c76be4TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/customprebuiltdomains/{culture}][%d] 59104d855aca2f0b48c76be4TooManyRequests ", 429)
}

func (o *Nr59104d855aca2f0b48c76be4TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
