// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr59388c545aca2f0e24581851Params creates a new Nr59388c545aca2f0e24581851Params object
// with the default values initialized.
func NewNr59388c545aca2f0e24581851Params() *Nr59388c545aca2f0e24581851Params {
	var ()
	return &Nr59388c545aca2f0e24581851Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr59388c545aca2f0e24581851ParamsWithTimeout creates a new Nr59388c545aca2f0e24581851Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr59388c545aca2f0e24581851ParamsWithTimeout(timeout time.Duration) *Nr59388c545aca2f0e24581851Params {
	var ()
	return &Nr59388c545aca2f0e24581851Params{

		timeout: timeout,
	}
}

// NewNr59388c545aca2f0e24581851ParamsWithContext creates a new Nr59388c545aca2f0e24581851Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr59388c545aca2f0e24581851ParamsWithContext(ctx context.Context) *Nr59388c545aca2f0e24581851Params {
	var ()
	return &Nr59388c545aca2f0e24581851Params{

		Context: ctx,
	}
}

// NewNr59388c545aca2f0e24581851ParamsWithHTTPClient creates a new Nr59388c545aca2f0e24581851Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr59388c545aca2f0e24581851ParamsWithHTTPClient(client *http.Client) *Nr59388c545aca2f0e24581851Params {
	var ()
	return &Nr59388c545aca2f0e24581851Params{
		HTTPClient: client,
	}
}

/*Nr59388c545aca2f0e24581851Params contains all the parameters to send to the API endpoint
for the 59388c545aca2f0e24581851 operation typically these are written to a http.Request
*/
type Nr59388c545aca2f0e24581851Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*Body
	  Model object containing new name of the hierarchical entity child.

	*/
	Body interface{}
	/*HChildID
	  Format - guid. The hierarchical entity extractor child ID.

	*/
	HChildID string
	/*HEntityID
	  Format - guid. The hierarchical entity extractor ID.

	*/
	HEntityID string
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithTimeout(timeout time.Duration) *Nr59388c545aca2f0e24581851Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithContext(ctx context.Context) *Nr59388c545aca2f0e24581851Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithHTTPClient(client *http.Client) *Nr59388c545aca2f0e24581851Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithAppID(appID string) *Nr59388c545aca2f0e24581851Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithBody adds the body to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithBody(body interface{}) *Nr59388c545aca2f0e24581851Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetBody(body interface{}) {
	o.Body = body
}

// WithHChildID adds the hChildID to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithHChildID(hChildID string) *Nr59388c545aca2f0e24581851Params {
	o.SetHChildID(hChildID)
	return o
}

// SetHChildID adds the hChildId to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetHChildID(hChildID string) {
	o.HChildID = hChildID
}

// WithHEntityID adds the hEntityID to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithHEntityID(hEntityID string) *Nr59388c545aca2f0e24581851Params {
	o.SetHEntityID(hEntityID)
	return o
}

// SetHEntityID adds the hEntityId to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetHEntityID(hEntityID string) {
	o.HEntityID = hEntityID
}

// WithVersionID adds the versionID to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) WithVersionID(versionID string) *Nr59388c545aca2f0e24581851Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 59388c545aca2f0e24581851 params
func (o *Nr59388c545aca2f0e24581851Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr59388c545aca2f0e24581851Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param hChildId
	if err := r.SetPathParam("hChildId", o.HChildID); err != nil {
		return err
	}

	// path param hEntityId
	if err := r.SetPathParam("hEntityId", o.HEntityID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
