// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr591047175aca2f0b48c76bddReader is a Reader for the Nr591047175aca2f0b48c76bdd structure.
type Nr591047175aca2f0b48c76bddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr591047175aca2f0b48c76bddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr591047175aca2f0b48c76bddCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr591047175aca2f0b48c76bddBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr591047175aca2f0b48c76bddUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr591047175aca2f0b48c76bddForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr591047175aca2f0b48c76bddTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr591047175aca2f0b48c76bddCreated creates a Nr591047175aca2f0b48c76bddCreated with default headers values
func NewNr591047175aca2f0b48c76bddCreated() *Nr591047175aca2f0b48c76bddCreated {
	return &Nr591047175aca2f0b48c76bddCreated{}
}

/*Nr591047175aca2f0b48c76bddCreated handles this case with default header values.

The ID of the created model.
*/
type Nr591047175aca2f0b48c76bddCreated struct {
}

func (o *Nr591047175aca2f0b48c76bddCreated) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/customprebuiltintents][%d] 591047175aca2f0b48c76bddCreated ", 201)
}

func (o *Nr591047175aca2f0b48c76bddCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr591047175aca2f0b48c76bddBadRequest creates a Nr591047175aca2f0b48c76bddBadRequest with default headers values
func NewNr591047175aca2f0b48c76bddBadRequest() *Nr591047175aca2f0b48c76bddBadRequest {
	return &Nr591047175aca2f0b48c76bddBadRequest{}
}

/*Nr591047175aca2f0b48c76bddBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing or malformed.

This error can be returned if the request's body are incorrect meaning the JSON is missing or malformed.
*/
type Nr591047175aca2f0b48c76bddBadRequest struct {
}

func (o *Nr591047175aca2f0b48c76bddBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/customprebuiltintents][%d] 591047175aca2f0b48c76bddBadRequest ", 400)
}

func (o *Nr591047175aca2f0b48c76bddBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr591047175aca2f0b48c76bddUnauthorized creates a Nr591047175aca2f0b48c76bddUnauthorized with default headers values
func NewNr591047175aca2f0b48c76bddUnauthorized() *Nr591047175aca2f0b48c76bddUnauthorized {
	return &Nr591047175aca2f0b48c76bddUnauthorized{}
}

/*Nr591047175aca2f0b48c76bddUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr591047175aca2f0b48c76bddUnauthorized struct {
}

func (o *Nr591047175aca2f0b48c76bddUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/customprebuiltintents][%d] 591047175aca2f0b48c76bddUnauthorized ", 401)
}

func (o *Nr591047175aca2f0b48c76bddUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr591047175aca2f0b48c76bddForbidden creates a Nr591047175aca2f0b48c76bddForbidden with default headers values
func NewNr591047175aca2f0b48c76bddForbidden() *Nr591047175aca2f0b48c76bddForbidden {
	return &Nr591047175aca2f0b48c76bddForbidden{}
}

/*Nr591047175aca2f0b48c76bddForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr591047175aca2f0b48c76bddForbidden struct {
}

func (o *Nr591047175aca2f0b48c76bddForbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/customprebuiltintents][%d] 591047175aca2f0b48c76bddForbidden ", 403)
}

func (o *Nr591047175aca2f0b48c76bddForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr591047175aca2f0b48c76bddTooManyRequests creates a Nr591047175aca2f0b48c76bddTooManyRequests with default headers values
func NewNr591047175aca2f0b48c76bddTooManyRequests() *Nr591047175aca2f0b48c76bddTooManyRequests {
	return &Nr591047175aca2f0b48c76bddTooManyRequests{}
}

/*Nr591047175aca2f0b48c76bddTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr591047175aca2f0b48c76bddTooManyRequests struct {
}

func (o *Nr591047175aca2f0b48c76bddTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/customprebuiltintents][%d] 591047175aca2f0b48c76bddTooManyRequests ", 429)
}

func (o *Nr591047175aca2f0b48c76bddTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
