// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5ade6328d5b81c209ce2e5b9Reader is a Reader for the Nr5ade6328d5b81c209ce2e5b9 structure.
type Nr5ade6328d5b81c209ce2e5b9Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5ade6328d5b81c209ce2e5b9Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5ade6328d5b81c209ce2e5b9OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5ade6328d5b81c209ce2e5b9BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5ade6328d5b81c209ce2e5b9Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5ade6328d5b81c209ce2e5b9Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5ade6328d5b81c209ce2e5b9TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5ade6328d5b81c209ce2e5b9OK creates a Nr5ade6328d5b81c209ce2e5b9OK with default headers values
func NewNr5ade6328d5b81c209ce2e5b9OK() *Nr5ade6328d5b81c209ce2e5b9OK {
	return &Nr5ade6328d5b81c209ce2e5b9OK{}
}

/*Nr5ade6328d5b81c209ce2e5b9OK handles this case with default header values.

The entity extractor role.
*/
type Nr5ade6328d5b81c209ce2e5b9OK struct {
}

func (o *Nr5ade6328d5b81c209ce2e5b9OK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/compositeentities/{cEntityId}/roles/{roleId}][%d] 5ade6328d5b81c209ce2e5b9OK ", 200)
}

func (o *Nr5ade6328d5b81c209ce2e5b9OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade6328d5b81c209ce2e5b9BadRequest creates a Nr5ade6328d5b81c209ce2e5b9BadRequest with default headers values
func NewNr5ade6328d5b81c209ce2e5b9BadRequest() *Nr5ade6328d5b81c209ce2e5b9BadRequest {
	return &Nr5ade6328d5b81c209ce2e5b9BadRequest{}
}

/*Nr5ade6328d5b81c209ce2e5b9BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5ade6328d5b81c209ce2e5b9BadRequest struct {
}

func (o *Nr5ade6328d5b81c209ce2e5b9BadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/compositeentities/{cEntityId}/roles/{roleId}][%d] 5ade6328d5b81c209ce2e5b9BadRequest ", 400)
}

func (o *Nr5ade6328d5b81c209ce2e5b9BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade6328d5b81c209ce2e5b9Unauthorized creates a Nr5ade6328d5b81c209ce2e5b9Unauthorized with default headers values
func NewNr5ade6328d5b81c209ce2e5b9Unauthorized() *Nr5ade6328d5b81c209ce2e5b9Unauthorized {
	return &Nr5ade6328d5b81c209ce2e5b9Unauthorized{}
}

/*Nr5ade6328d5b81c209ce2e5b9Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5ade6328d5b81c209ce2e5b9Unauthorized struct {
}

func (o *Nr5ade6328d5b81c209ce2e5b9Unauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/compositeentities/{cEntityId}/roles/{roleId}][%d] 5ade6328d5b81c209ce2e5b9Unauthorized ", 401)
}

func (o *Nr5ade6328d5b81c209ce2e5b9Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade6328d5b81c209ce2e5b9Forbidden creates a Nr5ade6328d5b81c209ce2e5b9Forbidden with default headers values
func NewNr5ade6328d5b81c209ce2e5b9Forbidden() *Nr5ade6328d5b81c209ce2e5b9Forbidden {
	return &Nr5ade6328d5b81c209ce2e5b9Forbidden{}
}

/*Nr5ade6328d5b81c209ce2e5b9Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5ade6328d5b81c209ce2e5b9Forbidden struct {
}

func (o *Nr5ade6328d5b81c209ce2e5b9Forbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/compositeentities/{cEntityId}/roles/{roleId}][%d] 5ade6328d5b81c209ce2e5b9Forbidden ", 403)
}

func (o *Nr5ade6328d5b81c209ce2e5b9Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade6328d5b81c209ce2e5b9TooManyRequests creates a Nr5ade6328d5b81c209ce2e5b9TooManyRequests with default headers values
func NewNr5ade6328d5b81c209ce2e5b9TooManyRequests() *Nr5ade6328d5b81c209ce2e5b9TooManyRequests {
	return &Nr5ade6328d5b81c209ce2e5b9TooManyRequests{}
}

/*Nr5ade6328d5b81c209ce2e5b9TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5ade6328d5b81c209ce2e5b9TooManyRequests struct {
}

func (o *Nr5ade6328d5b81c209ce2e5b9TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/compositeentities/{cEntityId}/roles/{roleId}][%d] 5ade6328d5b81c209ce2e5b9TooManyRequests ", 429)
}

func (o *Nr5ade6328d5b81c209ce2e5b9TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
