// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5ade0f32d5b81c209ce2e59dReader is a Reader for the Nr5ade0f32d5b81c209ce2e59d structure.
type Nr5ade0f32d5b81c209ce2e59dReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5ade0f32d5b81c209ce2e59dReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr5ade0f32d5b81c209ce2e59dCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5ade0f32d5b81c209ce2e59dBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5ade0f32d5b81c209ce2e59dUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5ade0f32d5b81c209ce2e59dForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5ade0f32d5b81c209ce2e59dTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5ade0f32d5b81c209ce2e59dCreated creates a Nr5ade0f32d5b81c209ce2e59dCreated with default headers values
func NewNr5ade0f32d5b81c209ce2e59dCreated() *Nr5ade0f32d5b81c209ce2e59dCreated {
	return &Nr5ade0f32d5b81c209ce2e59dCreated{}
}

/*Nr5ade0f32d5b81c209ce2e59dCreated handles this case with default header values.

The ID of the created role.
*/
type Nr5ade0f32d5b81c209ce2e59dCreated struct {
}

func (o *Nr5ade0f32d5b81c209ce2e59dCreated) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles][%d] 5ade0f32d5b81c209ce2e59dCreated ", 201)
}

func (o *Nr5ade0f32d5b81c209ce2e59dCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade0f32d5b81c209ce2e59dBadRequest creates a Nr5ade0f32d5b81c209ce2e59dBadRequest with default headers values
func NewNr5ade0f32d5b81c209ce2e59dBadRequest() *Nr5ade0f32d5b81c209ce2e59dBadRequest {
	return &Nr5ade0f32d5b81c209ce2e59dBadRequest{}
}

/*Nr5ade0f32d5b81c209ce2e59dBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5ade0f32d5b81c209ce2e59dBadRequest struct {
}

func (o *Nr5ade0f32d5b81c209ce2e59dBadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles][%d] 5ade0f32d5b81c209ce2e59dBadRequest ", 400)
}

func (o *Nr5ade0f32d5b81c209ce2e59dBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade0f32d5b81c209ce2e59dUnauthorized creates a Nr5ade0f32d5b81c209ce2e59dUnauthorized with default headers values
func NewNr5ade0f32d5b81c209ce2e59dUnauthorized() *Nr5ade0f32d5b81c209ce2e59dUnauthorized {
	return &Nr5ade0f32d5b81c209ce2e59dUnauthorized{}
}

/*Nr5ade0f32d5b81c209ce2e59dUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5ade0f32d5b81c209ce2e59dUnauthorized struct {
}

func (o *Nr5ade0f32d5b81c209ce2e59dUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles][%d] 5ade0f32d5b81c209ce2e59dUnauthorized ", 401)
}

func (o *Nr5ade0f32d5b81c209ce2e59dUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade0f32d5b81c209ce2e59dForbidden creates a Nr5ade0f32d5b81c209ce2e59dForbidden with default headers values
func NewNr5ade0f32d5b81c209ce2e59dForbidden() *Nr5ade0f32d5b81c209ce2e59dForbidden {
	return &Nr5ade0f32d5b81c209ce2e59dForbidden{}
}

/*Nr5ade0f32d5b81c209ce2e59dForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5ade0f32d5b81c209ce2e59dForbidden struct {
}

func (o *Nr5ade0f32d5b81c209ce2e59dForbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles][%d] 5ade0f32d5b81c209ce2e59dForbidden ", 403)
}

func (o *Nr5ade0f32d5b81c209ce2e59dForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade0f32d5b81c209ce2e59dTooManyRequests creates a Nr5ade0f32d5b81c209ce2e59dTooManyRequests with default headers values
func NewNr5ade0f32d5b81c209ce2e59dTooManyRequests() *Nr5ade0f32d5b81c209ce2e59dTooManyRequests {
	return &Nr5ade0f32d5b81c209ce2e59dTooManyRequests{}
}

/*Nr5ade0f32d5b81c209ce2e59dTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5ade0f32d5b81c209ce2e59dTooManyRequests struct {
}

func (o *Nr5ade0f32d5b81c209ce2e59dTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles][%d] 5ade0f32d5b81c209ce2e59dTooManyRequests ", 429)
}

func (o *Nr5ade0f32d5b81c209ce2e59dTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
