// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr5ade5c1ad5b81c209ce2e5b5Params creates a new Nr5ade5c1ad5b81c209ce2e5b5Params object
// with the default values initialized.
func NewNr5ade5c1ad5b81c209ce2e5b5Params() *Nr5ade5c1ad5b81c209ce2e5b5Params {
	var ()
	return &Nr5ade5c1ad5b81c209ce2e5b5Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5ade5c1ad5b81c209ce2e5b5ParamsWithTimeout creates a new Nr5ade5c1ad5b81c209ce2e5b5Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5ade5c1ad5b81c209ce2e5b5ParamsWithTimeout(timeout time.Duration) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	var ()
	return &Nr5ade5c1ad5b81c209ce2e5b5Params{

		timeout: timeout,
	}
}

// NewNr5ade5c1ad5b81c209ce2e5b5ParamsWithContext creates a new Nr5ade5c1ad5b81c209ce2e5b5Params object
// with the default values initialized, and the ability to set a context for a request
func NewNr5ade5c1ad5b81c209ce2e5b5ParamsWithContext(ctx context.Context) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	var ()
	return &Nr5ade5c1ad5b81c209ce2e5b5Params{

		Context: ctx,
	}
}

// NewNr5ade5c1ad5b81c209ce2e5b5ParamsWithHTTPClient creates a new Nr5ade5c1ad5b81c209ce2e5b5Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5ade5c1ad5b81c209ce2e5b5ParamsWithHTTPClient(client *http.Client) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	var ()
	return &Nr5ade5c1ad5b81c209ce2e5b5Params{
		HTTPClient: client,
	}
}

/*Nr5ade5c1ad5b81c209ce2e5b5Params contains all the parameters to send to the API endpoint
for the 5ade5c1ad5b81c209ce2e5b5 operation typically these are written to a http.Request
*/
type Nr5ade5c1ad5b81c209ce2e5b5Params struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*EntityID
	  Format - guid. The closed list entity ID.

	*/
	EntityID string
	/*RoleID
	  Format - guid. The role ID.

	*/
	RoleID string
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WithTimeout(timeout time.Duration) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WithContext(ctx context.Context) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WithHTTPClient(client *http.Client) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WithAppID(appID string) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) SetAppID(appID string) {
	o.AppID = appID
}

// WithEntityID adds the entityID to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WithEntityID(entityID string) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	o.SetEntityID(entityID)
	return o
}

// SetEntityID adds the entityId to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) SetEntityID(entityID string) {
	o.EntityID = entityID
}

// WithRoleID adds the roleID to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WithRoleID(roleID string) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	o.SetRoleID(roleID)
	return o
}

// SetRoleID adds the roleId to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) SetRoleID(roleID string) {
	o.RoleID = roleID
}

// WithVersionID adds the versionID to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WithVersionID(versionID string) *Nr5ade5c1ad5b81c209ce2e5b5Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 5ade5c1ad5b81c209ce2e5b5 params
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5ade5c1ad5b81c209ce2e5b5Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	// path param entityId
	if err := r.SetPathParam("entityId", o.EntityID); err != nil {
		return err
	}

	// path param roleId
	if err := r.SetPathParam("roleId", o.RoleID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
