// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5adf4a64d5b81c09bc0db022Reader is a Reader for the Nr5adf4a64d5b81c09bc0db022 structure.
type Nr5adf4a64d5b81c09bc0db022Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5adf4a64d5b81c09bc0db022Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5adf4a64d5b81c09bc0db022OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5adf4a64d5b81c09bc0db022BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5adf4a64d5b81c09bc0db022Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5adf4a64d5b81c09bc0db022Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5adf4a64d5b81c09bc0db022TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5adf4a64d5b81c09bc0db022OK creates a Nr5adf4a64d5b81c09bc0db022OK with default headers values
func NewNr5adf4a64d5b81c09bc0db022OK() *Nr5adf4a64d5b81c09bc0db022OK {
	return &Nr5adf4a64d5b81c09bc0db022OK{}
}

/*Nr5adf4a64d5b81c09bc0db022OK handles this case with default header values.

The list of patterns in the application
*/
type Nr5adf4a64d5b81c09bc0db022OK struct {
}

func (o *Nr5adf4a64d5b81c09bc0db022OK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4a64d5b81c09bc0db022OK ", 200)
}

func (o *Nr5adf4a64d5b81c09bc0db022OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4a64d5b81c09bc0db022BadRequest creates a Nr5adf4a64d5b81c09bc0db022BadRequest with default headers values
func NewNr5adf4a64d5b81c09bc0db022BadRequest() *Nr5adf4a64d5b81c09bc0db022BadRequest {
	return &Nr5adf4a64d5b81c09bc0db022BadRequest{}
}

/*Nr5adf4a64d5b81c09bc0db022BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.
*/
type Nr5adf4a64d5b81c09bc0db022BadRequest struct {
}

func (o *Nr5adf4a64d5b81c09bc0db022BadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4a64d5b81c09bc0db022BadRequest ", 400)
}

func (o *Nr5adf4a64d5b81c09bc0db022BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4a64d5b81c09bc0db022Unauthorized creates a Nr5adf4a64d5b81c09bc0db022Unauthorized with default headers values
func NewNr5adf4a64d5b81c09bc0db022Unauthorized() *Nr5adf4a64d5b81c09bc0db022Unauthorized {
	return &Nr5adf4a64d5b81c09bc0db022Unauthorized{}
}

/*Nr5adf4a64d5b81c09bc0db022Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5adf4a64d5b81c09bc0db022Unauthorized struct {
}

func (o *Nr5adf4a64d5b81c09bc0db022Unauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4a64d5b81c09bc0db022Unauthorized ", 401)
}

func (o *Nr5adf4a64d5b81c09bc0db022Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4a64d5b81c09bc0db022Forbidden creates a Nr5adf4a64d5b81c09bc0db022Forbidden with default headers values
func NewNr5adf4a64d5b81c09bc0db022Forbidden() *Nr5adf4a64d5b81c09bc0db022Forbidden {
	return &Nr5adf4a64d5b81c09bc0db022Forbidden{}
}

/*Nr5adf4a64d5b81c09bc0db022Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5adf4a64d5b81c09bc0db022Forbidden struct {
}

func (o *Nr5adf4a64d5b81c09bc0db022Forbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4a64d5b81c09bc0db022Forbidden ", 403)
}

func (o *Nr5adf4a64d5b81c09bc0db022Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4a64d5b81c09bc0db022TooManyRequests creates a Nr5adf4a64d5b81c09bc0db022TooManyRequests with default headers values
func NewNr5adf4a64d5b81c09bc0db022TooManyRequests() *Nr5adf4a64d5b81c09bc0db022TooManyRequests {
	return &Nr5adf4a64d5b81c09bc0db022TooManyRequests{}
}

/*Nr5adf4a64d5b81c09bc0db022TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5adf4a64d5b81c09bc0db022TooManyRequests struct {
}

func (o *Nr5adf4a64d5b81c09bc0db022TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4a64d5b81c09bc0db022TooManyRequests ", 429)
}

func (o *Nr5adf4a64d5b81c09bc0db022TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
