// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5aa7d98cd5b81c0b702579e6Reader is a Reader for the Nr5aa7d98cd5b81c0b702579e6 structure.
type Nr5aa7d98cd5b81c0b702579e6Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5aa7d98cd5b81c0b702579e6Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr5aa7d98cd5b81c0b702579e6Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5aa7d98cd5b81c0b702579e6BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5aa7d98cd5b81c0b702579e6Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5aa7d98cd5b81c0b702579e6Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5aa7d98cd5b81c0b702579e6TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5aa7d98cd5b81c0b702579e6Created creates a Nr5aa7d98cd5b81c0b702579e6Created with default headers values
func NewNr5aa7d98cd5b81c0b702579e6Created() *Nr5aa7d98cd5b81c0b702579e6Created {
	return &Nr5aa7d98cd5b81c0b702579e6Created{}
}

/*Nr5aa7d98cd5b81c0b702579e6Created handles this case with default header values.

The ID of the created model.
*/
type Nr5aa7d98cd5b81c0b702579e6Created struct {
}

func (o *Nr5aa7d98cd5b81c0b702579e6Created) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities][%d] 5aa7d98cd5b81c0b702579e6Created ", 201)
}

func (o *Nr5aa7d98cd5b81c0b702579e6Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5aa7d98cd5b81c0b702579e6BadRequest creates a Nr5aa7d98cd5b81c0b702579e6BadRequest with default headers values
func NewNr5aa7d98cd5b81c0b702579e6BadRequest() *Nr5aa7d98cd5b81c0b702579e6BadRequest {
	return &Nr5aa7d98cd5b81c0b702579e6BadRequest{}
}

/*Nr5aa7d98cd5b81c0b702579e6BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.

This error can be returned if you are attempting to create an entity when the max entity count is exceeded.
```
{
  "error": {
    "code": "BadArgument",
    "message": "An application cannot have more than 20 regex entities."
  }
}
```

This error is returned if the regex is invalid:
```
{
  "error": {
    "code": "BadArgument",
    "message": "Failed to parse regex entity extractor creation object. Parameter name: regexEntityExtractorCreateObj"
  }
}
```

*/
type Nr5aa7d98cd5b81c0b702579e6BadRequest struct {
}

func (o *Nr5aa7d98cd5b81c0b702579e6BadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities][%d] 5aa7d98cd5b81c0b702579e6BadRequest ", 400)
}

func (o *Nr5aa7d98cd5b81c0b702579e6BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5aa7d98cd5b81c0b702579e6Unauthorized creates a Nr5aa7d98cd5b81c0b702579e6Unauthorized with default headers values
func NewNr5aa7d98cd5b81c0b702579e6Unauthorized() *Nr5aa7d98cd5b81c0b702579e6Unauthorized {
	return &Nr5aa7d98cd5b81c0b702579e6Unauthorized{}
}

/*Nr5aa7d98cd5b81c0b702579e6Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5aa7d98cd5b81c0b702579e6Unauthorized struct {
}

func (o *Nr5aa7d98cd5b81c0b702579e6Unauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities][%d] 5aa7d98cd5b81c0b702579e6Unauthorized ", 401)
}

func (o *Nr5aa7d98cd5b81c0b702579e6Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5aa7d98cd5b81c0b702579e6Forbidden creates a Nr5aa7d98cd5b81c0b702579e6Forbidden with default headers values
func NewNr5aa7d98cd5b81c0b702579e6Forbidden() *Nr5aa7d98cd5b81c0b702579e6Forbidden {
	return &Nr5aa7d98cd5b81c0b702579e6Forbidden{}
}

/*Nr5aa7d98cd5b81c0b702579e6Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5aa7d98cd5b81c0b702579e6Forbidden struct {
}

func (o *Nr5aa7d98cd5b81c0b702579e6Forbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities][%d] 5aa7d98cd5b81c0b702579e6Forbidden ", 403)
}

func (o *Nr5aa7d98cd5b81c0b702579e6Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5aa7d98cd5b81c0b702579e6TooManyRequests creates a Nr5aa7d98cd5b81c0b702579e6TooManyRequests with default headers values
func NewNr5aa7d98cd5b81c0b702579e6TooManyRequests() *Nr5aa7d98cd5b81c0b702579e6TooManyRequests {
	return &Nr5aa7d98cd5b81c0b702579e6TooManyRequests{}
}

/*Nr5aa7d98cd5b81c0b702579e6TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5aa7d98cd5b81c0b702579e6TooManyRequests struct {
}

func (o *Nr5aa7d98cd5b81c0b702579e6TooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/regexentities][%d] 5aa7d98cd5b81c0b702579e6TooManyRequests ", 429)
}

func (o *Nr5aa7d98cd5b81c0b702579e6TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
