// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNr5aa7e16cd5b81c0b702579ebParams creates a new Nr5aa7e16cd5b81c0b702579ebParams object
// with the default values initialized.
func NewNr5aa7e16cd5b81c0b702579ebParams() *Nr5aa7e16cd5b81c0b702579ebParams {
	var ()
	return &Nr5aa7e16cd5b81c0b702579ebParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNr5aa7e16cd5b81c0b702579ebParamsWithTimeout creates a new Nr5aa7e16cd5b81c0b702579ebParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNr5aa7e16cd5b81c0b702579ebParamsWithTimeout(timeout time.Duration) *Nr5aa7e16cd5b81c0b702579ebParams {
	var ()
	return &Nr5aa7e16cd5b81c0b702579ebParams{

		timeout: timeout,
	}
}

// NewNr5aa7e16cd5b81c0b702579ebParamsWithContext creates a new Nr5aa7e16cd5b81c0b702579ebParams object
// with the default values initialized, and the ability to set a context for a request
func NewNr5aa7e16cd5b81c0b702579ebParamsWithContext(ctx context.Context) *Nr5aa7e16cd5b81c0b702579ebParams {
	var ()
	return &Nr5aa7e16cd5b81c0b702579ebParams{

		Context: ctx,
	}
}

// NewNr5aa7e16cd5b81c0b702579ebParamsWithHTTPClient creates a new Nr5aa7e16cd5b81c0b702579ebParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNr5aa7e16cd5b81c0b702579ebParamsWithHTTPClient(client *http.Client) *Nr5aa7e16cd5b81c0b702579ebParams {
	var ()
	return &Nr5aa7e16cd5b81c0b702579ebParams{
		HTTPClient: client,
	}
}

/*Nr5aa7e16cd5b81c0b702579ebParams contains all the parameters to send to the API endpoint
for the 5aa7e16cd5b81c0b702579eb operation typically these are written to a http.Request
*/
type Nr5aa7e16cd5b81c0b702579ebParams struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*Body
	  A json object containing the new regular expression entity name and pattern.

	*/
	Body interface{}
	/*RegexEntityID
	  Format - guid. The regular expression entity extractor ID.

	*/
	RegexEntityID string
	/*VersionID
	  The task version ID.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WithTimeout(timeout time.Duration) *Nr5aa7e16cd5b81c0b702579ebParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WithContext(ctx context.Context) *Nr5aa7e16cd5b81c0b702579ebParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WithHTTPClient(client *http.Client) *Nr5aa7e16cd5b81c0b702579ebParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WithAppID(appID string) *Nr5aa7e16cd5b81c0b702579ebParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithBody adds the body to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WithBody(body interface{}) *Nr5aa7e16cd5b81c0b702579ebParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) SetBody(body interface{}) {
	o.Body = body
}

// WithRegexEntityID adds the regexEntityID to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WithRegexEntityID(regexEntityID string) *Nr5aa7e16cd5b81c0b702579ebParams {
	o.SetRegexEntityID(regexEntityID)
	return o
}

// SetRegexEntityID adds the regexEntityId to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) SetRegexEntityID(regexEntityID string) {
	o.RegexEntityID = regexEntityID
}

// WithVersionID adds the versionID to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WithVersionID(versionID string) *Nr5aa7e16cd5b81c0b702579ebParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the 5aa7e16cd5b81c0b702579eb params
func (o *Nr5aa7e16cd5b81c0b702579ebParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *Nr5aa7e16cd5b81c0b702579ebParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param regexEntityId
	if err := r.SetPathParam("regexEntityId", o.RegexEntityID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
