// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5ade550bd5b81c209ce2e5a8Reader is a Reader for the Nr5ade550bd5b81c209ce2e5a8 structure.
type Nr5ade550bd5b81c209ce2e5a8Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5ade550bd5b81c209ce2e5a8Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr5ade550bd5b81c209ce2e5a8Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5ade550bd5b81c209ce2e5a8BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5ade550bd5b81c209ce2e5a8Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5ade550bd5b81c209ce2e5a8Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5ade550bd5b81c209ce2e5a8TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5ade550bd5b81c209ce2e5a8Created creates a Nr5ade550bd5b81c209ce2e5a8Created with default headers values
func NewNr5ade550bd5b81c209ce2e5a8Created() *Nr5ade550bd5b81c209ce2e5a8Created {
	return &Nr5ade550bd5b81c209ce2e5a8Created{}
}

/*Nr5ade550bd5b81c209ce2e5a8Created handles this case with default header values.

The id of the newly explicit list item
*/
type Nr5ade550bd5b81c209ce2e5a8Created struct {
}

func (o *Nr5ade550bd5b81c209ce2e5a8Created) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist][%d] 5ade550bd5b81c209ce2e5a8Created ", 201)
}

func (o *Nr5ade550bd5b81c209ce2e5a8Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade550bd5b81c209ce2e5a8BadRequest creates a Nr5ade550bd5b81c209ce2e5a8BadRequest with default headers values
func NewNr5ade550bd5b81c209ce2e5a8BadRequest() *Nr5ade550bd5b81c209ce2e5a8BadRequest {
	return &Nr5ade550bd5b81c209ce2e5a8BadRequest{}
}

/*Nr5ade550bd5b81c209ce2e5a8BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.

This error can be returned if the request's body is incorrect meaning the JSON is missing, malformed, or too large.
*/
type Nr5ade550bd5b81c209ce2e5a8BadRequest struct {
}

func (o *Nr5ade550bd5b81c209ce2e5a8BadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist][%d] 5ade550bd5b81c209ce2e5a8BadRequest ", 400)
}

func (o *Nr5ade550bd5b81c209ce2e5a8BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade550bd5b81c209ce2e5a8Unauthorized creates a Nr5ade550bd5b81c209ce2e5a8Unauthorized with default headers values
func NewNr5ade550bd5b81c209ce2e5a8Unauthorized() *Nr5ade550bd5b81c209ce2e5a8Unauthorized {
	return &Nr5ade550bd5b81c209ce2e5a8Unauthorized{}
}

/*Nr5ade550bd5b81c209ce2e5a8Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5ade550bd5b81c209ce2e5a8Unauthorized struct {
}

func (o *Nr5ade550bd5b81c209ce2e5a8Unauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist][%d] 5ade550bd5b81c209ce2e5a8Unauthorized ", 401)
}

func (o *Nr5ade550bd5b81c209ce2e5a8Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade550bd5b81c209ce2e5a8Forbidden creates a Nr5ade550bd5b81c209ce2e5a8Forbidden with default headers values
func NewNr5ade550bd5b81c209ce2e5a8Forbidden() *Nr5ade550bd5b81c209ce2e5a8Forbidden {
	return &Nr5ade550bd5b81c209ce2e5a8Forbidden{}
}

/*Nr5ade550bd5b81c209ce2e5a8Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5ade550bd5b81c209ce2e5a8Forbidden struct {
}

func (o *Nr5ade550bd5b81c209ce2e5a8Forbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist][%d] 5ade550bd5b81c209ce2e5a8Forbidden ", 403)
}

func (o *Nr5ade550bd5b81c209ce2e5a8Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade550bd5b81c209ce2e5a8TooManyRequests creates a Nr5ade550bd5b81c209ce2e5a8TooManyRequests with default headers values
func NewNr5ade550bd5b81c209ce2e5a8TooManyRequests() *Nr5ade550bd5b81c209ce2e5a8TooManyRequests {
	return &Nr5ade550bd5b81c209ce2e5a8TooManyRequests{}
}

/*Nr5ade550bd5b81c209ce2e5a8TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5ade550bd5b81c209ce2e5a8TooManyRequests struct {
}

func (o *Nr5ade550bd5b81c209ce2e5a8TooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist][%d] 5ade550bd5b81c209ce2e5a8TooManyRequests ", 429)
}

func (o *Nr5ade550bd5b81c209ce2e5a8TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
