// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5adf4d1fd5b81c09bc0db023Reader is a Reader for the Nr5adf4d1fd5b81c09bc0db023 structure.
type Nr5adf4d1fd5b81c09bc0db023Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5adf4d1fd5b81c09bc0db023Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5adf4d1fd5b81c09bc0db023OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5adf4d1fd5b81c09bc0db023BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5adf4d1fd5b81c09bc0db023Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5adf4d1fd5b81c09bc0db023Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5adf4d1fd5b81c09bc0db023TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5adf4d1fd5b81c09bc0db023OK creates a Nr5adf4d1fd5b81c09bc0db023OK with default headers values
func NewNr5adf4d1fd5b81c09bc0db023OK() *Nr5adf4d1fd5b81c09bc0db023OK {
	return &Nr5adf4d1fd5b81c09bc0db023OK{}
}

/*Nr5adf4d1fd5b81c09bc0db023OK handles this case with default header values.

The updated patterns
*/
type Nr5adf4d1fd5b81c09bc0db023OK struct {
}

func (o *Nr5adf4d1fd5b81c09bc0db023OK) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4d1fd5b81c09bc0db023OK ", 200)
}

func (o *Nr5adf4d1fd5b81c09bc0db023OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4d1fd5b81c09bc0db023BadRequest creates a Nr5adf4d1fd5b81c09bc0db023BadRequest with default headers values
func NewNr5adf4d1fd5b81c09bc0db023BadRequest() *Nr5adf4d1fd5b81c09bc0db023BadRequest {
	return &Nr5adf4d1fd5b81c09bc0db023BadRequest{}
}

/*Nr5adf4d1fd5b81c09bc0db023BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5adf4d1fd5b81c09bc0db023BadRequest struct {
}

func (o *Nr5adf4d1fd5b81c09bc0db023BadRequest) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4d1fd5b81c09bc0db023BadRequest ", 400)
}

func (o *Nr5adf4d1fd5b81c09bc0db023BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4d1fd5b81c09bc0db023Unauthorized creates a Nr5adf4d1fd5b81c09bc0db023Unauthorized with default headers values
func NewNr5adf4d1fd5b81c09bc0db023Unauthorized() *Nr5adf4d1fd5b81c09bc0db023Unauthorized {
	return &Nr5adf4d1fd5b81c09bc0db023Unauthorized{}
}

/*Nr5adf4d1fd5b81c09bc0db023Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5adf4d1fd5b81c09bc0db023Unauthorized struct {
}

func (o *Nr5adf4d1fd5b81c09bc0db023Unauthorized) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4d1fd5b81c09bc0db023Unauthorized ", 401)
}

func (o *Nr5adf4d1fd5b81c09bc0db023Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4d1fd5b81c09bc0db023Forbidden creates a Nr5adf4d1fd5b81c09bc0db023Forbidden with default headers values
func NewNr5adf4d1fd5b81c09bc0db023Forbidden() *Nr5adf4d1fd5b81c09bc0db023Forbidden {
	return &Nr5adf4d1fd5b81c09bc0db023Forbidden{}
}

/*Nr5adf4d1fd5b81c09bc0db023Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5adf4d1fd5b81c09bc0db023Forbidden struct {
}

func (o *Nr5adf4d1fd5b81c09bc0db023Forbidden) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4d1fd5b81c09bc0db023Forbidden ", 403)
}

func (o *Nr5adf4d1fd5b81c09bc0db023Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5adf4d1fd5b81c09bc0db023TooManyRequests creates a Nr5adf4d1fd5b81c09bc0db023TooManyRequests with default headers values
func NewNr5adf4d1fd5b81c09bc0db023TooManyRequests() *Nr5adf4d1fd5b81c09bc0db023TooManyRequests {
	return &Nr5adf4d1fd5b81c09bc0db023TooManyRequests{}
}

/*Nr5adf4d1fd5b81c09bc0db023TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5adf4d1fd5b81c09bc0db023TooManyRequests struct {
}

func (o *Nr5adf4d1fd5b81c09bc0db023TooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternrules][%d] 5adf4d1fd5b81c09bc0db023TooManyRequests ", 429)
}

func (o *Nr5adf4d1fd5b81c09bc0db023TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
