// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5ade676bd5b81c209ce2e5c6Reader is a Reader for the Nr5ade676bd5b81c209ce2e5c6 structure.
type Nr5ade676bd5b81c209ce2e5c6Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5ade676bd5b81c209ce2e5c6Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5ade676bd5b81c209ce2e5c6OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5ade676bd5b81c209ce2e5c6BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5ade676bd5b81c209ce2e5c6Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5ade676bd5b81c209ce2e5c6Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5ade676bd5b81c209ce2e5c6TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5ade676bd5b81c209ce2e5c6OK creates a Nr5ade676bd5b81c209ce2e5c6OK with default headers values
func NewNr5ade676bd5b81c209ce2e5c6OK() *Nr5ade676bd5b81c209ce2e5c6OK {
	return &Nr5ade676bd5b81c209ce2e5c6OK{}
}

/*Nr5ade676bd5b81c209ce2e5c6OK handles this case with default header values.

Nr5ade676bd5b81c209ce2e5c6OK 5ade676bd5b81c209ce2e5c6 o k
*/
type Nr5ade676bd5b81c209ce2e5c6OK struct {
}

func (o *Nr5ade676bd5b81c209ce2e5c6OK) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist/{itemId}][%d] 5ade676bd5b81c209ce2e5c6OK ", 200)
}

func (o *Nr5ade676bd5b81c209ce2e5c6OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade676bd5b81c209ce2e5c6BadRequest creates a Nr5ade676bd5b81c209ce2e5c6BadRequest with default headers values
func NewNr5ade676bd5b81c209ce2e5c6BadRequest() *Nr5ade676bd5b81c209ce2e5c6BadRequest {
	return &Nr5ade676bd5b81c209ce2e5c6BadRequest{}
}

/*Nr5ade676bd5b81c209ce2e5c6BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5ade676bd5b81c209ce2e5c6BadRequest struct {
}

func (o *Nr5ade676bd5b81c209ce2e5c6BadRequest) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist/{itemId}][%d] 5ade676bd5b81c209ce2e5c6BadRequest ", 400)
}

func (o *Nr5ade676bd5b81c209ce2e5c6BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade676bd5b81c209ce2e5c6Unauthorized creates a Nr5ade676bd5b81c209ce2e5c6Unauthorized with default headers values
func NewNr5ade676bd5b81c209ce2e5c6Unauthorized() *Nr5ade676bd5b81c209ce2e5c6Unauthorized {
	return &Nr5ade676bd5b81c209ce2e5c6Unauthorized{}
}

/*Nr5ade676bd5b81c209ce2e5c6Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5ade676bd5b81c209ce2e5c6Unauthorized struct {
}

func (o *Nr5ade676bd5b81c209ce2e5c6Unauthorized) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist/{itemId}][%d] 5ade676bd5b81c209ce2e5c6Unauthorized ", 401)
}

func (o *Nr5ade676bd5b81c209ce2e5c6Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade676bd5b81c209ce2e5c6Forbidden creates a Nr5ade676bd5b81c209ce2e5c6Forbidden with default headers values
func NewNr5ade676bd5b81c209ce2e5c6Forbidden() *Nr5ade676bd5b81c209ce2e5c6Forbidden {
	return &Nr5ade676bd5b81c209ce2e5c6Forbidden{}
}

/*Nr5ade676bd5b81c209ce2e5c6Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5ade676bd5b81c209ce2e5c6Forbidden struct {
}

func (o *Nr5ade676bd5b81c209ce2e5c6Forbidden) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist/{itemId}][%d] 5ade676bd5b81c209ce2e5c6Forbidden ", 403)
}

func (o *Nr5ade676bd5b81c209ce2e5c6Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade676bd5b81c209ce2e5c6TooManyRequests creates a Nr5ade676bd5b81c209ce2e5c6TooManyRequests with default headers values
func NewNr5ade676bd5b81c209ce2e5c6TooManyRequests() *Nr5ade676bd5b81c209ce2e5c6TooManyRequests {
	return &Nr5ade676bd5b81c209ce2e5c6TooManyRequests{}
}

/*Nr5ade676bd5b81c209ce2e5c6TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5ade676bd5b81c209ce2e5c6TooManyRequests struct {
}

func (o *Nr5ade676bd5b81c209ce2e5c6TooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /apps/{appId}/versions/{versionId}/patternanyentities/{entityId}/explicitlist/{itemId}][%d] 5ade676bd5b81c209ce2e5c6TooManyRequests ", 429)
}

func (o *Nr5ade676bd5b81c209ce2e5c6TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
