// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5ade602bd5b81c209ce2e5b6Reader is a Reader for the Nr5ade602bd5b81c209ce2e5b6 structure.
type Nr5ade602bd5b81c209ce2e5b6Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5ade602bd5b81c209ce2e5b6Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNr5ade602bd5b81c209ce2e5b6OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5ade602bd5b81c209ce2e5b6BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5ade602bd5b81c209ce2e5b6Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5ade602bd5b81c209ce2e5b6Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5ade602bd5b81c209ce2e5b6TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5ade602bd5b81c209ce2e5b6OK creates a Nr5ade602bd5b81c209ce2e5b6OK with default headers values
func NewNr5ade602bd5b81c209ce2e5b6OK() *Nr5ade602bd5b81c209ce2e5b6OK {
	return &Nr5ade602bd5b81c209ce2e5b6OK{}
}

/*Nr5ade602bd5b81c209ce2e5b6OK handles this case with default header values.

The entity extractor role.
*/
type Nr5ade602bd5b81c209ce2e5b6OK struct {
}

func (o *Nr5ade602bd5b81c209ce2e5b6OK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles/{roleId}][%d] 5ade602bd5b81c209ce2e5b6OK ", 200)
}

func (o *Nr5ade602bd5b81c209ce2e5b6OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade602bd5b81c209ce2e5b6BadRequest creates a Nr5ade602bd5b81c209ce2e5b6BadRequest with default headers values
func NewNr5ade602bd5b81c209ce2e5b6BadRequest() *Nr5ade602bd5b81c209ce2e5b6BadRequest {
	return &Nr5ade602bd5b81c209ce2e5b6BadRequest{}
}

/*Nr5ade602bd5b81c209ce2e5b6BadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type Nr5ade602bd5b81c209ce2e5b6BadRequest struct {
}

func (o *Nr5ade602bd5b81c209ce2e5b6BadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles/{roleId}][%d] 5ade602bd5b81c209ce2e5b6BadRequest ", 400)
}

func (o *Nr5ade602bd5b81c209ce2e5b6BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade602bd5b81c209ce2e5b6Unauthorized creates a Nr5ade602bd5b81c209ce2e5b6Unauthorized with default headers values
func NewNr5ade602bd5b81c209ce2e5b6Unauthorized() *Nr5ade602bd5b81c209ce2e5b6Unauthorized {
	return &Nr5ade602bd5b81c209ce2e5b6Unauthorized{}
}

/*Nr5ade602bd5b81c209ce2e5b6Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type Nr5ade602bd5b81c209ce2e5b6Unauthorized struct {
}

func (o *Nr5ade602bd5b81c209ce2e5b6Unauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles/{roleId}][%d] 5ade602bd5b81c209ce2e5b6Unauthorized ", 401)
}

func (o *Nr5ade602bd5b81c209ce2e5b6Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade602bd5b81c209ce2e5b6Forbidden creates a Nr5ade602bd5b81c209ce2e5b6Forbidden with default headers values
func NewNr5ade602bd5b81c209ce2e5b6Forbidden() *Nr5ade602bd5b81c209ce2e5b6Forbidden {
	return &Nr5ade602bd5b81c209ce2e5b6Forbidden{}
}

/*Nr5ade602bd5b81c209ce2e5b6Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5ade602bd5b81c209ce2e5b6Forbidden struct {
}

func (o *Nr5ade602bd5b81c209ce2e5b6Forbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles/{roleId}][%d] 5ade602bd5b81c209ce2e5b6Forbidden ", 403)
}

func (o *Nr5ade602bd5b81c209ce2e5b6Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5ade602bd5b81c209ce2e5b6TooManyRequests creates a Nr5ade602bd5b81c209ce2e5b6TooManyRequests with default headers values
func NewNr5ade602bd5b81c209ce2e5b6TooManyRequests() *Nr5ade602bd5b81c209ce2e5b6TooManyRequests {
	return &Nr5ade602bd5b81c209ce2e5b6TooManyRequests{}
}

/*Nr5ade602bd5b81c209ce2e5b6TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5ade602bd5b81c209ce2e5b6TooManyRequests struct {
}

func (o *Nr5ade602bd5b81c209ce2e5b6TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/regexentities/{entityId}/roles/{roleId}][%d] 5ade602bd5b81c209ce2e5b6TooManyRequests ", 429)
}

func (o *Nr5ade602bd5b81c209ce2e5b6TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
