// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// Nr5be32228e8473de116325515Reader is a Reader for the Nr5be32228e8473de116325515 structure.
type Nr5be32228e8473de116325515Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Nr5be32228e8473de116325515Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewNr5be32228e8473de116325515Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNr5be32228e8473de116325515BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewNr5be32228e8473de116325515Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewNr5be32228e8473de116325515Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewNr5be32228e8473de116325515TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNr5be32228e8473de116325515Created creates a Nr5be32228e8473de116325515Created with default headers values
func NewNr5be32228e8473de116325515Created() *Nr5be32228e8473de116325515Created {
	return &Nr5be32228e8473de116325515Created{}
}

/*Nr5be32228e8473de116325515Created handles this case with default header values.

A message indicating success of operation.
*/
type Nr5be32228e8473de116325515Created struct {
}

func (o *Nr5be32228e8473de116325515Created) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/azureaccounts][%d] 5be32228e8473de116325515Created ", 201)
}

func (o *Nr5be32228e8473de116325515Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5be32228e8473de116325515BadRequest creates a Nr5be32228e8473de116325515BadRequest with default headers values
func NewNr5be32228e8473de116325515BadRequest() *Nr5be32228e8473de116325515BadRequest {
	return &Nr5be32228e8473de116325515BadRequest{}
}

/*Nr5be32228e8473de116325515BadRequest handles this case with default header values.

The app ID is missing or invalid.
The includeResponse is invalid.
*/
type Nr5be32228e8473de116325515BadRequest struct {
}

func (o *Nr5be32228e8473de116325515BadRequest) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/azureaccounts][%d] 5be32228e8473de116325515BadRequest ", 400)
}

func (o *Nr5be32228e8473de116325515BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5be32228e8473de116325515Unauthorized creates a Nr5be32228e8473de116325515Unauthorized with default headers values
func NewNr5be32228e8473de116325515Unauthorized() *Nr5be32228e8473de116325515Unauthorized {
	return &Nr5be32228e8473de116325515Unauthorized{}
}

/*Nr5be32228e8473de116325515Unauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls

*/
type Nr5be32228e8473de116325515Unauthorized struct {
}

func (o *Nr5be32228e8473de116325515Unauthorized) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/azureaccounts][%d] 5be32228e8473de116325515Unauthorized ", 401)
}

func (o *Nr5be32228e8473de116325515Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5be32228e8473de116325515Forbidden creates a Nr5be32228e8473de116325515Forbidden with default headers values
func NewNr5be32228e8473de116325515Forbidden() *Nr5be32228e8473de116325515Forbidden {
	return &Nr5be32228e8473de116325515Forbidden{}
}

/*Nr5be32228e8473de116325515Forbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type Nr5be32228e8473de116325515Forbidden struct {
}

func (o *Nr5be32228e8473de116325515Forbidden) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/azureaccounts][%d] 5be32228e8473de116325515Forbidden ", 403)
}

func (o *Nr5be32228e8473de116325515Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNr5be32228e8473de116325515TooManyRequests creates a Nr5be32228e8473de116325515TooManyRequests with default headers values
func NewNr5be32228e8473de116325515TooManyRequests() *Nr5be32228e8473de116325515TooManyRequests {
	return &Nr5be32228e8473de116325515TooManyRequests{}
}

/*Nr5be32228e8473de116325515TooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type Nr5be32228e8473de116325515TooManyRequests struct {
}

func (o *Nr5be32228e8473de116325515TooManyRequests) Error() string {
	return fmt.Sprintf("[POST /apps/{appId}/azureaccounts][%d] 5be32228e8473de116325515TooManyRequests ", 429)
}

func (o *Nr5be32228e8473de116325515TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
