// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRenameSubscriptionKeyParams creates a new RenameSubscriptionKeyParams object
// with the default values initialized.
func NewRenameSubscriptionKeyParams() *RenameSubscriptionKeyParams {
	var ()
	return &RenameSubscriptionKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRenameSubscriptionKeyParamsWithTimeout creates a new RenameSubscriptionKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRenameSubscriptionKeyParamsWithTimeout(timeout time.Duration) *RenameSubscriptionKeyParams {
	var ()
	return &RenameSubscriptionKeyParams{

		timeout: timeout,
	}
}

// NewRenameSubscriptionKeyParamsWithContext creates a new RenameSubscriptionKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewRenameSubscriptionKeyParamsWithContext(ctx context.Context) *RenameSubscriptionKeyParams {
	var ()
	return &RenameSubscriptionKeyParams{

		Context: ctx,
	}
}

// NewRenameSubscriptionKeyParamsWithHTTPClient creates a new RenameSubscriptionKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRenameSubscriptionKeyParamsWithHTTPClient(client *http.Client) *RenameSubscriptionKeyParams {
	var ()
	return &RenameSubscriptionKeyParams{
		HTTPClient: client,
	}
}

/*RenameSubscriptionKeyParams contains all the parameters to send to the API endpoint
for the rename subscription key operation typically these are written to a http.Request
*/
type RenameSubscriptionKeyParams struct {

	/*Body
	  Subscription key object.

	*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the rename subscription key params
func (o *RenameSubscriptionKeyParams) WithTimeout(timeout time.Duration) *RenameSubscriptionKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rename subscription key params
func (o *RenameSubscriptionKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rename subscription key params
func (o *RenameSubscriptionKeyParams) WithContext(ctx context.Context) *RenameSubscriptionKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rename subscription key params
func (o *RenameSubscriptionKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rename subscription key params
func (o *RenameSubscriptionKeyParams) WithHTTPClient(client *http.Client) *RenameSubscriptionKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rename subscription key params
func (o *RenameSubscriptionKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rename subscription key params
func (o *RenameSubscriptionKeyParams) WithBody(body interface{}) *RenameSubscriptionKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rename subscription key params
func (o *RenameSubscriptionKeyParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RenameSubscriptionKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
