// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SuggestIntentExamplesReader is a Reader for the SuggestIntentExamples structure.
type SuggestIntentExamplesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SuggestIntentExamplesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSuggestIntentExamplesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSuggestIntentExamplesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSuggestIntentExamplesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSuggestIntentExamplesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewSuggestIntentExamplesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSuggestIntentExamplesOK creates a SuggestIntentExamplesOK with default headers values
func NewSuggestIntentExamplesOK() *SuggestIntentExamplesOK {
	return &SuggestIntentExamplesOK{}
}

/*SuggestIntentExamplesOK handles this case with default header values.

|Trained|Untrained|
|-----|----|
| If the active learning algorithm finds any relevant queries, they are returned with the model predictions.

If the active learning algorithm didn't find any relevant queries, an empty list is returned in the response.| Nothing is returned|
*/
type SuggestIntentExamplesOK struct {
}

func (o *SuggestIntentExamplesOK) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] suggestIntentExamplesOK ", 200)
}

func (o *SuggestIntentExamplesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSuggestIntentExamplesBadRequest creates a SuggestIntentExamplesBadRequest with default headers values
func NewSuggestIntentExamplesBadRequest() *SuggestIntentExamplesBadRequest {
	return &SuggestIntentExamplesBadRequest{}
}

/*SuggestIntentExamplesBadRequest handles this case with default header values.

This error can be returned if the request's parameters are incorrect meaning the required parameters are missing, malformed, or too large.
*/
type SuggestIntentExamplesBadRequest struct {
}

func (o *SuggestIntentExamplesBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] suggestIntentExamplesBadRequest ", 400)
}

func (o *SuggestIntentExamplesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSuggestIntentExamplesUnauthorized creates a SuggestIntentExamplesUnauthorized with default headers values
func NewSuggestIntentExamplesUnauthorized() *SuggestIntentExamplesUnauthorized {
	return &SuggestIntentExamplesUnauthorized{}
}

/*SuggestIntentExamplesUnauthorized handles this case with default header values.

You do not have access.

Reasons can include:

* used endpoint subscription key, instead of authoring key
* invalid, malformed, or empty authoring key
* authoring key doesn't match region
* you are not the owner or collaborator
* invalid order of API calls
*/
type SuggestIntentExamplesUnauthorized struct {
}

func (o *SuggestIntentExamplesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] suggestIntentExamplesUnauthorized ", 401)
}

func (o *SuggestIntentExamplesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSuggestIntentExamplesForbidden creates a SuggestIntentExamplesForbidden with default headers values
func NewSuggestIntentExamplesForbidden() *SuggestIntentExamplesForbidden {
	return &SuggestIntentExamplesForbidden{}
}

/*SuggestIntentExamplesForbidden handles this case with default header values.

Total monthly key quota limit exceeded
*/
type SuggestIntentExamplesForbidden struct {
}

func (o *SuggestIntentExamplesForbidden) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] suggestIntentExamplesForbidden ", 403)
}

func (o *SuggestIntentExamplesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSuggestIntentExamplesTooManyRequests creates a SuggestIntentExamplesTooManyRequests with default headers values
func NewSuggestIntentExamplesTooManyRequests() *SuggestIntentExamplesTooManyRequests {
	return &SuggestIntentExamplesTooManyRequests{}
}

/*SuggestIntentExamplesTooManyRequests handles this case with default header values.

Rate limit is exceeded.
*/
type SuggestIntentExamplesTooManyRequests struct {
}

func (o *SuggestIntentExamplesTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /apps/{appId}/versions/{versionId}/intents/{intentId}/suggest][%d] suggestIntentExamplesTooManyRequests ", 429)
}

func (o *SuggestIntentExamplesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
