// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateAccessListParams creates a new UpdateAccessListParams object
// with the default values initialized.
func NewUpdateAccessListParams() *UpdateAccessListParams {
	var ()
	return &UpdateAccessListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAccessListParamsWithTimeout creates a new UpdateAccessListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAccessListParamsWithTimeout(timeout time.Duration) *UpdateAccessListParams {
	var ()
	return &UpdateAccessListParams{

		timeout: timeout,
	}
}

// NewUpdateAccessListParamsWithContext creates a new UpdateAccessListParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAccessListParamsWithContext(ctx context.Context) *UpdateAccessListParams {
	var ()
	return &UpdateAccessListParams{

		Context: ctx,
	}
}

// NewUpdateAccessListParamsWithHTTPClient creates a new UpdateAccessListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAccessListParamsWithHTTPClient(client *http.Client) *UpdateAccessListParams {
	var ()
	return &UpdateAccessListParams{
		HTTPClient: client,
	}
}

/*UpdateAccessListParams contains all the parameters to send to the API endpoint
for the update access list operation typically these are written to a http.Request
*/
type UpdateAccessListParams struct {

	/*AppID
	  Format - guid. The application ID.

	*/
	AppID string
	/*Body
	  A JSON object containing a list of user's email addresses.


	*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update access list params
func (o *UpdateAccessListParams) WithTimeout(timeout time.Duration) *UpdateAccessListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update access list params
func (o *UpdateAccessListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update access list params
func (o *UpdateAccessListParams) WithContext(ctx context.Context) *UpdateAccessListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update access list params
func (o *UpdateAccessListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update access list params
func (o *UpdateAccessListParams) WithHTTPClient(client *http.Client) *UpdateAccessListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update access list params
func (o *UpdateAccessListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the update access list params
func (o *UpdateAccessListParams) WithAppID(appID string) *UpdateAccessListParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the update access list params
func (o *UpdateAccessListParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithBody adds the body to the update access list params
func (o *UpdateAccessListParams) WithBody(body interface{}) *UpdateAccessListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update access list params
func (o *UpdateAccessListParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccessListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
