// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// KeyValue key value
// swagger:model KeyValue
type KeyValue string

// Validate validates this key value
func (m KeyValue) Validate(formats strfmt.Registry) error {
	return nil
}
