// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PhraselistCreateObject phraselist create object
// swagger:model PhraselistCreateObject
type PhraselistCreateObject struct {

	// is exchangeable
	IsExchangeable *bool `json:"IsExchangeable,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// phrases
	Phrases string `json:"Phrases,omitempty"`
}

// Validate validates this phraselist create object
func (m *PhraselistCreateObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhraselistCreateObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhraselistCreateObject) UnmarshalBinary(b []byte) error {
	var res PhraselistCreateObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
