// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PhraselistUpdateObject phraselist update object
// swagger:model PhraselistUpdateObject
type PhraselistUpdateObject struct {

	// is active
	IsActive *bool `json:"IsActive,omitempty"`

	// is exchangeable
	IsExchangeable *bool `json:"IsExchangeable,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// phrases
	Phrases string `json:"Phrases,omitempty"`
}

// Validate validates this phraselist update object
func (m *PhraselistUpdateObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhraselistUpdateObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhraselistUpdateObject) UnmarshalBinary(b []byte) error {
	var res PhraselistUpdateObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
