// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WordListBaseUpdateObject word list base update object
// swagger:model WordListBaseUpdateObject
type WordListBaseUpdateObject struct {

	// canonical form
	CanonicalForm string `json:"CanonicalForm,omitempty"`

	// list
	List []string `json:"List"`
}

// Validate validates this word list base update object
func (m *WordListBaseUpdateObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WordListBaseUpdateObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WordListBaseUpdateObject) UnmarshalBinary(b []byte) error {
	var res WordListBaseUpdateObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
